### ISSUE TITLE
EHIS ametikoht

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#10]
Tagasiside koolilt "Kas EHIS-e ametikoha valikul on võimalik teha nii, et kui sisestan kutseõppeasutust puudutavat infot, siis mulle avanebki vaid kutseõppega seotud ametikohtade loend? Meil ei ole uurijaid ega teadureid, professoreid ega vanemassistente. See lühendaks olemasolevat loendit."

Kas seda on võimalik teostada?

**Comment by irinakelder** [comment]
Jah, pugi

**Comment by Lendaja** [comment]
Tehtud (v 0.3.0).

**Comment by Helenvaltmann** [comment]
aitäh, toimib
