### ISSUE TITLE
Aineprogrammid - Tallinna Tervishoiu Kõrgkool

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#102]
Tänud vastuse eest! Ma loodan, et jääb siis vähemalt ÕIS1 miinimum, et võimalik lisada failina aineprogrammi. 2016. aastal otsustasime, et hakkame kasutama ÕIS1 funktsionaalsust. Andsime tagasisidet ja tänu teie arendajale saime korraliku mooduli, mida kasutada.
Järjepidevalt on tööd tehtud õppejõududega, et nad selle mooduli omaks võtaksid. Sellel sügisel on positiivne tulemus, et õppejõud aktiivselt seda kasutavad ja õppurid saavad ühest kohast aineprogrammid kätte. Väga hea on astmesüsteem kinnitamiseks, mis tähendab, et kõik kinnitamisele minevad programmid käivad kontrollitult ka õppekava juhi arvutilaualt läbi. 
ÕIS2 oleks praegusel kujul täielik tagasilöök. Osa aineprogrammi välju on õppeaine andmete all. Ma ei hakka hetkel musta stsenaariumit ette kujutama, kus õppejõu keskseid välju hakkab õppejõu asemel administratiivtöötaja sisestama, mis toob tagasi ellu paberil liikuva info ühest kohast teise. ÕIS1-s hetkel ikkagi õppejõud ise sisestab oma aines hindamiskriteeriumid, iseseisva töö, kirjanduse etc  Jään lihtsalt huviga ootama, mis ÕIS2l selles osas varuks on.
Ma olen kahe käega poolt standardiseerimise poolt. Kui põhjendatakse, miks see nii mõistlikum, siis miks ka mitte. 
/Kristiina Pullerits

**Comment by Pirgit** [comment]
II etapis tuleb kogu aineprogrammide loogika ja menetlemine läbi analüüsida ja teostada.

**Comment by AnuPiirisild** [comment]
Soov tõstetud Confluence arendusettepanekutesse aineprogrammide teema juurde.
