### ISSUE TITLE
H&F Hindamisviisid - Tallinna Tervishoiu Kõrgkool

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#103]
Minnes veidi kõrvale aineprogrammist ja rääkides õppeaine hindamisviisidest, siis on mul siin samuti mure. Nimelt, hindamisviis on meil ainult eristav või mitteeristav. Me ei too siin eraldi välja eksamit, arvestust ja hindelist arvestust. Kuna on õpiväljundi põhine hindamine, siis me ei erista, et hindelise arvestuse puhul hindame õpiväljundeid nõrgemini kui nt eksamil. See muutus ÕIS2ga, kus me ei saa määratleda, kuidas me oma hindamisviisi väljendame tähendaks meile õppekorralduseeskirja muutmist selles osas. Hea võimalus oleks, kes seda tahab, määratleb eksami/hindelise arvestuse/arvestuse, kuid võiks jääda koolil võimalus ka ainult mitteeristavaks ja eristavaks hindamiseks. Kas see on midagi, mis on ka EHISe klassifikaatoritest selliselt kirjas? Ma ise ei leidnud viidet sellisele jaotusele EHISe juhendites.
Kristiina Pullerits

**Comment by Helenvaltmann** [comment]
arutame Lembega

**Comment by Pirgit** [comment]
Peaadministraatoril on võimalik õppeaine hindamisviise lisada.
