### ISSUE TITLE
H&F Õppekava - moodulid - üldõpingute moodulid - erisus, vene keelga õperühmadele

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#106]
Üldõpingute mooduli all on 5 ekapit rohkem ja nii ei saa neid klappima kogu mooduli mahuga, sest 5 on rohkem. Praegu aga programm kontrollib ja seda koolid ka tahtsid. Mida teha, Pirgitiga arutada?

**Comment by Helenvaltmann** [comment]
arutada Lembega mis saaks teha.

**Comment by irinakelder** [comment]
RÕK/KUTSE ÕK mooduli sisestamine – lisada märkeruut „lisamoodul“ 
Uus tunnus selleks, et oleks võimalik lisada moodulit, mille maht ei võeta arvesse õppekava kogumahu kontrollimiseks ehk siis märkeruudu valimisel sisestatud mooduli maht ignoreeritakse mahu kontrolli käigus. 
Vaikimisi tühi

**Comment by Lendaja** [comment]
tehtud ver 0.5
