### ISSUE TITLE
H&F Kas suletud rakenduskava peaks saama muuta, hilisemaks uurimiseks TTK

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#108]
Tere!

Sisestan ÕIS2s rakenduskava. Kuna rakenduskava teemade juures avastasin, et üks õpiväljund õppekava moodulis jäi sisestamata. Läksin õppekava juurde. Avasin mooduli, kuid ei andnud enam võimalust lisada moodulisse õpiväljundit („Lisa“ nupp on nähtaval, kuid ei tee midagi, kui peale vajutada). Kuna testimisel pole nii oluline teksti sisu, siis läksin tagasi rakenduskava juurde, kuid staatuseks oli nüüd „suletud“ ja ma midagi rakenduskavas muuta ei saa. Staatust ei saa ise muuta.
Tegutsen Chrome`s. Mida teha?

Heade soovidega

Kristiina Pullerits
õppekvaliteedijuht
Tallinna Tervishoiu Kõrgkool
6711 767
Õppurite vastuvõtuajad kohapeal (ruum 102): E-N 10:00-12:30; 14:00-16:00
-----
Tere, Kristiina

Ma uurin hiljem kas suletud rakenduskava peab saama muuta aga seniks kopeeri Lapsehoidja rakenduskava. 
Ps. ma tegin homseks testimiseks Sepa õppekava, nii et testimise eesmärgil on meil õppekava rakenduskavaga olemas ka. 

Helen

**Comment by Helenvaltmann** [comment]
Lembega läbi arutada.

**Comment by irinakelder** [comment]
Suletud rakenduskava muuta ei saa.
