### ISSUE TITLE
Kutseõppe kutsestandard ei ilmu kooli õppekava valikusse (TTK)

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#109]
Kool kirjutas: Eile Pirgitiga koos vaatasime ÕIS2-s lapsehoidja kinnitamise probleemi (küsib kutset). Tuli välja, et süsteemis oli lapsehoidja kutsestandard kehtetu. Pirgit küll muutis peaadmini alt kehtivust, kuid kui täna proovisin lisada kutset, siis lapsehoidjat siiski nimekirjas polnud. Ehk on Sul võimalus see uuesti üle vaadata. Kutsekoja lehel olevad andmed: https://www.kutsekoda.ee/et/kutseregister/kutsestandardid/10622201.

Helen : vaatasin järgi ja tõesti on klassifikaatorite all lapsehoidja 4. taseme kutsestandard olemas ja samuti on tal linnukesed, et on kutseõppele. 
Kui aga õppekavale valida, siis seda valikutesse ei tule. Palun abi! 

Sisse tuleb logida TTK 47810018476.

**Comment by Lendaja** [comment]
Antud juhul ei olnud valitud märkeruut "Õppekaval omandatakse kutse". See tähendab, et tegemist on osakutse õppekavaga ja kui kutsega ei ole seotud ühtegi osakutset, siis seda kutset ka nimekirjas ei kuvata.

**Comment by Helenvaltmann** [comment]
tänan, koolile vastus saadetud.
