### ISSUE TITLE
Kutseõppe õppekava sisestamisel ei saa jätkuõpet valida

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#11]
Proovisin kõikide alustega kutseõppe õppekava sisestada ning jätkuõpet ei saanud ühegi puhul valida.

**Comment by irinakelder** [comment]
Jätkuõpet ei saagi valida, sõltub eelnevalt valitud õppetasemest, mis peab olema jätkuõpe.
Kas on esmaõpe või jätkuõpe, seda ainult kuvatakse.

**Comment by Pirgit** [comment]
Valisin õppetasemeks jätkuõpe
![image](https://cloud.githubusercontent.com/assets/17288515/25475143/77deba56-2b3e-11e7-9a35-45d6e077a74d.png)

**Comment by irinakelder** [comment]
Jätkuõpe on readonly, sõltub valitud õppetasemest, hetkel on viga

**Comment by Lendaja** [comment]
Tehtud (v 0.3.0).

**Comment by Helenvaltmann** [comment]
toimib väga kenati, kui valida Õppekava kaardil õppetase Jätkuõpe (443 näiteks), siis muudab tarkvara ise ära jätkuõppe õppekavaks.
