### ISSUE TITLE
Õppekava - kõrghariduse õppekava sisestamine - Mooduli sisestamisel väike kirjaviga

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#111]
Õpetatava mooduli lisamisel on väike kirjavige - Mooduli liigi nimetue eesti keeles. 
Pilt lisatud. 
![oppekava moodul](https://user-images.githubusercontent.com/26483158/31814129-4e48d932-b591-11e7-9c82-3fdf3c5f0ff1.png)

**Comment by Lendaja** [comment]
tehtud ver 0.5
