### ISSUE TITLE
Sündmuse lisamise võimalus (Kuressaare Ametikool)

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#112]
Tunniplaani peab saama lisada eraldi sündmuseid (näen, et see koht on olemas aga tundub, et hetkel ei toimi) Sündmuste lisamisel peab olema võimalus lisada korraga mitu õpetajat ja mitu gruppi (hetkel on siseveebis selline võimalus olemas ainult ei saa lisada kohe mitut õpetajat korraga, loodame, et uues versioonis on see juba võimalik), samuti grupipõhiselt üksikuid õpilasi.

**Comment by Helenvaltmann** [comment]
arutame Lembega mis seis hetkel on

**Comment by irinakelder** [comment]
Lisada võimalus lisada mitu õpetajat ja ruumi. Gruppi ja üksikinimese lisamist ei tee

**Comment by Helenvaltmann** [comment]
Koolile vastus saadetud

**Comment by Pirgit** [comment]
Saab lisada mitu õpetajat ja ruumi.
