### ISSUE TITLE
Kattuvuste näitamine planeerimisel (Kuressaare ametikool)

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#114]
•	Planeerimine peab näitama ruumide ja õpetajate kattuvusi, ning äraolekud peavad samuti planeeringus nähtavad olema (siseveebi näide)
![kur2](https://user-images.githubusercontent.com/26483158/31818198-c4e28878-b59f-11e7-9f53-d8152d7641f1.png)
![kur3](https://user-images.githubusercontent.com/26483158/31818200-c7b9d880-b59f-11e7-88e9-5d73e0f93050.png)

**Comment by Helenvaltmann** [comment]
vaatame Lembega koos üle kuidas on hetkel ja kas on vaja veel miskit teha.

**Comment by irinakelder** [comment]
Tuleb kuvada kattuvus

**Comment by AnuPiirisild** [comment]
Ruumi ja õpetaja kattuvuse teadet ei tule. Testis sain panna samasse ruumi sama õpetaja erinevatele rühmadele:
![image](https://user-images.githubusercontent.com/36628933/38087185-e322d05c-335f-11e8-93f5-3678810f221c.png)
Versioon 0.6.6.

_Analüüsis: 3.5.2.1. p14. . Kui ruum või õpetaja on juba sel ajal hõivatud, väljastatakse teade „Ruum on hõivatud. Kas soovid jätkata?“ või „Õpetaja on hõivatud, kas soovid jätkata?“_

**Comment by AnuPiirisild** [comment]
Ruumi ja õpetaja kattuvuse kontroll toimib, sh ka siis, kui õpetaja on eelnevalt endal kalendris üksiksündmuse sisestanud. _Testitud versioonis 0.7.0._
(Eeldefineeritud vihjeriba tunniplaani koostajale, mis aegadel õptaja saab käia - tõstetud II etapi arendusse.)
