### ISSUE TITLE
Planeerimine - praktika klotsid ei tohiks ilmuda (Kuressaare ametikool)

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#116]
Planeerimisse ei tohiks lisanduda praktika „klotsid“ va juhul kui tegemist on tõesti koolis toimuva praktikaga ja iseseisevtöö.

**Comment by Helenvaltmann** [comment]
aruada Lembega kuidas on tehtav, et tuleksid ainult need, mida soovitakse planeerida, need mis määratakse kontakttunniks vms

**Comment by irinakelder** [comment]
Esimeses etapis ei tee

**Comment by Pirgit** [comment]
Kooli poolne seadistus, milliseid mahu jaotise valikuid nad kasutavad ja millised lisatakse tunniplaani. Lahendatakse II etapis.

**Comment by AnuPiirisild** [comment]
Lahendatud
