### ISSUE TITLE
Tunnijaotuse päise külmutamise võimalus (Kuressaare ametikool)

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#117]
Tunnijaotuses peaks päis nö külmutatud st kui lehte alla kerin ei kaoks perioodi nädal ära

**Comment by Helenvaltmann** [comment]
arutada Lembega, kas on tehtav

**Comment by irinakelder** [comment]
1. Uurime kas same päist külmutada
2. Tunnijaotusplaani sisestamise vormil uue päeviku lisamisel, vana päeviku muutmisel või Tagasi nupu vajutamisel süsteem peab andmed salvestama (eelnevalt üle küsides)

**Comment by Helenvaltmann** [comment]
Koolile vastatud: Arendaja võtab selle I etapi tööplaani ja vaatab kuidas on võimalik antud asja lahendada.

**Comment by Lendaja** [comment]
punkt 2 tehtud ver 0.6.0

punkt 1 on suurem töö

**Comment by Lendaja** [comment]
Tehtud ver 0.6.8
