### ISSUE TITLE
Tunnijaotuse planeering - koormuste kontroll, teated (Kuressaare Ametikool)

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#118]
Tunnijaotuses tunde planeerides peaks mingi mahu juures arvestama ka õp.koormuseid st. andma mingi veateate, et antud õp nädalane koormus on lubatust suurem

**Comment by Helenvaltmann** [comment]
hetkel annab selle teate kui lisada koormusi õppeainete koormuste lisamise all. Anda neile see info ja siis uurida täpsemalt kus ja mis hetkel peab nende jaoks teate andma.

**Comment by Helenvaltmann** [comment]
Koolile vastatud: Kas küsitud on õpetaja või õppeaine koormuse kohta? Õppeainet planeerides ei luba ÕIS üldisest mahust üle minna aga nädala lõikes võib rohkem planeerida, peaasi, et üldine maht lõhki ei läheks.

**Comment by AnuPiirisild** [comment]
Arendussoov tõstetud Confluences koormuste analüüsi teema juurde.
