### ISSUE TITLE
Otsingu filtrites osatekstiotsing

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#12]
Omandatava kutse lisamisel võiks saada kutset otsida osatekstiotsinguna. Praegu võimaldab otsida ainult esitähe järgi.

Kui teha sinna osatekstiotsing, siis võiks see olla süsteemis läbivalt nii.

**Comment by irinakelder** [comment]
Ei leidnud, mida konkreetselt mõelnud
