### ISSUE TITLE
H&F Vabade ruumide otsing (Kuressaare ametikool)

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#120]
Näide lisatud siseveebi kohta
![kur6](https://user-images.githubusercontent.com/26483158/31818431-c102dc70-b5a0-11e7-82af-3fdb89a76c20.png)

**Comment by Helenvaltmann** [comment]
jah see on teema, mis ka ÕIS1 hetkel on väga aktuaalne, et broneerimisel peaks nägema vabu ruume või siis oleks võimalik välja võtta vabu ruume.  Arutame Fujitsuga.

**Comment by irinakelder** [comment]
Esimeses etapis ei tee

**Comment by Helenvaltmann** [comment]
Koolile vastatud : Esimeses etapis sellisel kujul ei tule aga kui tunniplaani planeerida, kuvatakse kinnised ruumid punasega.  Võtame II etapis uuesti teemaks.

**Comment by AnuPiirisild** [comment]
_Tõstetud Jirasse: TAHVEL-55_
