### ISSUE TITLE
Koolibussi täituvus (Kuressaare Ametikool)

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#121]
Meie kooli eripärana peab olema võimalik saada kätte erinevaid andmeid.
N: busside liikumine Kuressaare-Upa-Kuressaare – õpilaste arvu 
helen : ei saa aru kus seda nägema peaks

**Comment by Helenvaltmann** [comment]
vaja koolilt täiendavalt küsida, et kus on soov näha.

**Comment by Helenvaltmann** [comment]
Koolilt küsitud: Palun täpsustage kust seda infot on soov kätte saada? Kuhu ja kuidas seda hetkel sisestatakse?

**Comment by AnuPiirisild** [comment]
Küsimus tõstetud ootele Confluence arendusettepanekute alla.
