### ISSUE TITLE
Teavitamine aegade planeerimisel (Kuressaare ametikool)

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#122]
Õpetajate äraoleku kinnitamisel peaks juhtõpetajale tulema teade, et antud õpetajal on sinna nädalasse planeeritud nii ja nii palju tunde ja millistele gruppidele, et juhtõpetaja saaks teavitada teisi juhtõpetajaid.

Helen: siit ei loe välja mis hetkel ja kus see tulema peab

**Comment by Helenvaltmann** [comment]
see vajab täpsutamist kunagi kui teavitamiste teemaga tegeleme.

**Comment by Helenvaltmann** [comment]
Hetkel ei ole plaanis ning I etappi ei mahu. Paneme selle soovi kirja II etapi arendusvajaduste ajaks

**Comment by Pirgit** [comment]
Lisaks tuleks II etapis lisada sel juhul ka õpetajate äraolekute kinnitamine.

**Comment by AnuPiirisild** [comment]
On vahepeal edasiarendatud ning tegeletakse jätkuvalt.
