### ISSUE TITLE
H&F Täiendusõpe (Kuressaare Ametikool)

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#123]
Üks murekoht on meil aga veel – täiend- ja ümberõpe. Hetkel on siseveebis olemas ja tun-nijaotus ja –plaan tulevad nagu tasemeõppijate omad. Ma ei tea ÕIS2 viimaseid suundi, aga algul oli juttu, et täiendõpet sinna ei tule. Kui seisukoht on endine ja täiendõpet ÕIS2-te plaanitud ei ole, toob see kaasa selle, et endiselt ei ole ühte keskkonda kogu kooli tegevus-te planeerimiseks. 
Kui aga plaanitakse see ikkagi teha, siis võiks olla võimalik teha tunnijaotusest õpetajate koormuste osas eraldi väljavõtted täiendõppe ja tasemeõppe
tundide osas. Praegu on see käsitöö ja meelespidamine, et kellelgi ei saaks tunnid topelt arvestatud.

Helen : minu  meelest on selleks Juhan

**Comment by Helenvaltmann** [comment]
See tuleb kindlasti läbi arutada ja peaks ka mõtlema kas peaks hakkama neile ka JUHANIt sooviama ja seda vajadusel liidestama kui mõelda topelt andmete sisestamisele?

**Comment by irinakelder** [comment]
Esimeses etapis ei tee (märksõna Juhan)

**Comment by Helenvaltmann** [comment]
Jah, täiendõppe asja tuleb kunagi eraldi arutada aga tuleks ikkagi neile Juhanit hakata pakkuma. Juhani projektijuht tegeleb ka sellega tasapisi, et kutsekoolidele ja teiste süsteemi pakkuda.

**Comment by Helenvaltmann** [comment]
Koolile vastatud: Antud teemaga on endiselt nii, et täiendõpet ÕIS2 ei tule. Selleks on meil olemas täiendusõppe infosüsteem Juhan ja II etappi on planeeritud ÕIS2 ja Juhani liidestused. Eesmärk on ikka see, et andmeid ei sisestataks mitmekordselt.
