### ISSUE TITLE
Tunniplaani soovid (Tallinna Ehituskool)

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#124]
Tere
 
nagu kokkulepitud oli, saadan teile omapoolsed ettepanekud/tähelepanekud seoses ÕIS2 arendusega.
Pildid on manuses.
 
1) Palun XML faili importimise võimalust ( kasutan aSc Timetables programmi). 
2) Palun võimalust lisada teksti õppetöögraafiku " klotsidesse".  ÕIS-i õppetöögraafik on meie õppeaasta ametlik ajaline plaan, mille alusel on planeeritud kogu õppeaasta õppetöö. Seda peavad  täitma valdkonna juhtõpetajad ja mina täiendan ja muudan(  ka IT-juht ja õppedirektor saavad vajadusel muuta ). Näha aga saavad kõik õpetajad.
3) Palun võimaldada ühtset moodulipäeviku vormi koos lõimingute lisamisega. Kuna seda koolis teen ainult mina, siis äärmiselt tähtis on, et ma saan kogu vajaliku info sisestada korraga ühele vormile.
 
Kui on täiendavaid küsimusi, siis olen valmis seletama.
 
Tervitades,
 
Kristina Hallikas
 
Tallinna Ehituskool
õppetöökorralduse juht
tel. nr : +372 58 607 684
![paeviku vaade koos loimingutega](https://user-images.githubusercontent.com/26483158/31818579-75a9b536-b5a1-11e7-9668-1f54ff39106e.PNG)
![paeviku vaade koos loimingutega_eriala opetaja](https://user-images.githubusercontent.com/26483158/31818580-75c97bc8-b5a1-11e7-95ab-891b7a5f7ae3.PNG)
![paeviku vaade koos loimingutega_loimitud ained](https://user-images.githubusercontent.com/26483158/31818581-75e926ee-b5a1-11e7-809e-4bcdb7c7b2cb.PNG)
![paeviku vaade koos loimingutega_loimitud ained2](https://user-images.githubusercontent.com/26483158/31818583-76082738-b5a1-11e7-8412-437021559363.png)
![paeviku vaade koos loimingutega_loimitud ained3](https://user-images.githubusercontent.com/26483158/31818584-7626d3b8-b5a1-11e7-9eb1-172993387181.PNG)
![tunniplaani import xml](https://user-images.githubusercontent.com/26483158/31818585-7651bf42-b5a1-11e7-878c-69f9a241da44.PNG)
![tuunijaotuskava_paeviku vorm koos loimingutega](https://user-images.githubusercontent.com/26483158/31818587-766bf696-b5a1-11e7-8754-76326665603e.PNG)
![tuunijaotuskava_paeviku vorm koos loimingutega2](https://user-images.githubusercontent.com/26483158/31818588-769914be-b5a1-11e7-89ae-8026daa191b1.PNG)
![tuunijaotuskava_paeviku vorm koos loimingutega3](https://user-images.githubusercontent.com/26483158/31818589-76b3695e-b5a1-11e7-9b92-7ce6855da71a.png)
![otg_teksti lisamine](https://user-images.githubusercontent.com/26483158/31818590-76d3b4f2-b5a1-11e7-8fd3-a264243e2a96.PNG)
![otg_teksti lisamine2](https://user-images.githubusercontent.com/26483158/31818591-76eefb9a-b5a1-11e7-8900-f9a52ba60380.PNG)
![otg_teksti lisamine3](https://user-images.githubusercontent.com/26483158/31818592-7709b570-b5a1-11e7-9f95-e2bbf34b9a9b.PNG)
![otg_teksti lisamine4](https://user-images.githubusercontent.com/26483158/31818593-77226be2-b5a1-11e7-9e2c-7f0850b60250.PNG)
![otg_teksti lisamine5](https://user-images.githubusercontent.com/26483158/31818594-773c7910-b5a1-11e7-8862-52838e45dff9.png)

**Comment by AnuPiirisild** [comment]
Tõstetud arendusettepanekutesse.
