### ISSUE TITLE
Tunniplaani kuvamine ja printimine (EBS)

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#125]
24.10 konsortsiumil avaldasid nad soovi, et tunniplaan võiks päeva laiuse kuvada vastavalt aine nimetuse pikkusele. Palusin neil näite saata ja seda nad ka kohe tegid.
Samas ma ei ole kindel, et seda teha saab, sest mõnedel on ainenimetused ikka väga pikad.
Pilt lisatud.
Arutame kunagi.

**Comment by Helenvaltmann** [comment]
![tunniplaanebs valjatrukk](https://user-images.githubusercontent.com/26483158/31946188-d47dffaa-b8d9-11e7-83fa-5ce79a301c9c.jpg)

**Comment by irinakelder** [comment]
Print Excelisse

**Comment by AnuPiirisild** [comment]
Tunniplaani osa eraldi teemaks.
