### ISSUE TITLE
Kutseõpetaja tunnijaotusplaan - kinnitaja, täitja - mis täpselt tähendab? (Pärnumaa)

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#126]
Olen täitja, Olen kinnitaja? Mis need tähendavad? Kas peale kinnitamist ei saa õpetaja planeeringut enam keegi muuta? Või kes saab, kes mitte? Mul tunniplaani tegijana tuleb pidevalt neid numbreid lähetuste, haigestumiste jms. tõttu muuta. Muutjad on ka osakonnajuhatajad ja nende asetäitjad.

Vaatame Pirgitiga koos 2.11 läi

**Comment by Pirgit** [comment]
Täitja ja kinnitaja on päeviku kohta, vastavalt sellele, kes saab päevikut kinnitada. Peale päeviku kinnitamist saab ainult admin muuta. Peab saama ka kinnitust maha võtta aga hetkel on see vigane. 

Tunnijaotuskava saab igal ajal muuta, see ei lähe lukku.
