### ISSUE TITLE
Õppekava salvestamine kui kõik kohustuslikud väljad ei ole täidetud

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#13]
1. Õppekava peaks saama poolikult salvestada. 
2. Salvestamisel peaks andma ka veateate - hetkel kui ainult üleval pool on kohustuslikud väljad täitmata, siis ei saa sellest aru, milles probleem on. 

Kooli kommentaar: 
Õppekava salvestamisel (juhul, kui õppekava ei salvestu) ei tule mingit teadet, kas salvestus või mitte. Ainult kohustuslikud väljad lähevad punaseks. Kui mõni kohustuslik väli on täitmata, siis õppekava ei salvestu. Peaks olema võimalik salvestada ka poole pealt, nii et osa välju on täitmata. Muidu ei julgegi õppekava sisestamisega tegelema hakata, kui just ei tea, et päev otsa selleks aega on.

**Comment by Pirgit** [comment]
Probleemi on tõstatatud mõlema taseme õppekavade puhul

**Comment by Helenvaltmann** [comment]
Lisan täiendavat infot. Peab olema vahepealne salvestamise võimalus, tekib märge ‘sisestamisel’/’pooleli’ (vmt)!!! või liigendada plokkide kaupa.
 Hitsa kommentaar : Kutsehariduseõppekava puhul on sama ettepanek edastatud. Teeme seda mõlema õppekava osas.

**Comment by irinakelder** [comment]
Õppekava nimetus, õppetase, EKAP/EAP jm põhiandmed jäävad kohustuslikuks, muud on kohustuslikud alles menetlemisse saatmisel

**Comment by Lendaja** [comment]
Tehtud (v 0.3.0).

**Comment by Helenvaltmann** [comment]
Kui täita kohustuslikud väljad ära, siis saab salvestada ja staatus on sisestamisel
