### ISSUE TITLE
H&F Kutseõpetaja tunnijaotusplaan - mooduli nime kuvamine Lisa päevikus (Pärnumaa)

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#130]
•	Kui ma hakkan mooduli alla uut päevikut sisestama, siis avaneb aine lisamine. Samas võiks kuskil näha jääda samal ajal ka mooduli nimi. Mina suutsin näiteks aine lisamisel mooduli nime korraks unustada ja kuskilt vaadata kohe ka polnud. Pidin tagasi minema vaatama, väga tüütu.

**Comment by Helenvaltmann** [comment]
Õppetoo ettevalmistus - kutseõppe tunnijaotusplaan . muuda/lisa - võiks olla Lisa päevik lehel ka mooduli nimetus, et seda ära ei unustaks. 
![moodulinimetus](https://user-images.githubusercontent.com/26483158/32175534-eef6eff0-bd8d-11e7-98d0-f01fbc869eba.png)

Arutadakoosolekul

**Comment by irinakelder** [comment]
Lisada rühma nime juurde ka mooduli nimi
