### ISSUE TITLE
H&F Tunniplaani haldamine - värvi määramine õpetajate kaupa - kas on võimalik? (Pärnumaa)

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#134]
•	Kas tunniplaani tegemisel saaks igale õpetajale koodi ja värvi määrata? Värvilised kastid hõlbustavad visuaalselt tööd. Kõik must-valged kaovad ühtsesse massi ära. Samas ma vaatan tunniplaani alt, et igal ainel on oma värv. See teeb pildi ikka õige kirjuks. Üldhariduskoolis on tõesti vaid 15 ainet ja saab igale ainele värvi määrata, kuid ma vaatasin, et meil on hetkel ligi 2000 ainet! Jääks ikka õpetaja värvi juurde, on lihtsam.

**Comment by Helenvaltmann** [comment]
arutame koos mis variandid meil on.

**Comment by irinakelder** [comment]
Esimeses etapis ei tee

**Comment by Helenvaltmann** [comment]
koolile vastatud

**Comment by AnuPiirisild** [comment]
Edaspidisel arutelul. Hetkel teema suletud.
