### ISSUE TITLE
H&F Tunniplaani haldamine - aine ja õpetaja kuvamine tunnikastile liikudes (Pärnumaa)

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#136]
•	Tunnikastile minnes peab ikka nägema, mis ainega ja õpetajaga tegu. Aine praegu on ja tunniliik ka, kuid pigem näidaku ikka, ainet ja õpetajat. Tunniliik ikka teisejärguline. Praegu tuleb õpetaja nime nägemiseks hiirega klõpsata ja avaneb uus aken. Aknaid küll nagu ei tahaks, see segab tööd.

**Comment by Helenvaltmann** [comment]
Aine nimi ja õpetaja nimi võiksid olla kuvatud kui kastile liikuda. Arutame kas on tehtav.

**Comment by irinakelder** [comment]
Hiirega liikudes
1) kuvada õpetaja(id)
2) õppetöö liiki mitte kuvada

**Comment by Lendaja** [comment]
Kutseõppes kuvatakse aine, õppetöö liik ja õpetaja(d) ver 0.6.6

**Comment by Helenvaltmann** [comment]
aitäh
