### ISSUE TITLE
H&F Tunniplaani haldamine - võimalus lisada rohkem tunde kui planeeritud  (Pärnumaa)

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#137]
•	Tundub, kui on ettenähtud tundide arv, siis rohkem tunde lisada ei saa? Kas selleks, et rohkem tunde panna nädalasse, pean tunnijaotuskavasse minema, seal ära muutma ja siis saab? Praeguses ÕIS-s saab vastupidi ka, lisan rohkem tunde ja siis lähen korrigeerin tunnijaotuskava ära.

**Comment by Helenvaltmann** [comment]
Pirgiti mäletamist mööda peaks selle kohta juba olema soov ja lahendusvariant olemas, et tehakse nupp mis võimaldab rohkem tunde lisada. 
Räägime koosolekul üle.

**Comment by irinakelder** [comment]
Juba tehtud, kuid ei ole üle antud. Mahtu perioodide lõikes ületada ei saa

**Comment by Helenvaltmann** [comment]
koolile ka info saadetud
