### ISSUE TITLE
Tunniplaani haldamine - õpetaja kaupa

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#138]
Kui ma tahan näiteks ühe õpetaja tunnid, kellel on näiteks kümnes rühmas tunnid, ära paigutada, siis kas mul on need tunnid seal Planeeritavad tunnid kõik läbisegi ees? Kuidas ma tuvastan, et konkreetne kast on just sellele rühmale? Proovimise teel? Metoodikaid on erinevaid ja üldjuhul tehakse tunniplaani rühmade kaupa, kuid ka õpetajate kaupa peaks saama mugavalt teha. Et paigutan näiteks kõik selle õpetaja tunnid, kes ainult teatud aegadel saab käia, tunniplaanidesse esimesena ära.

**Comment by Helenvaltmann** [comment]
Kui planeerida nt kahe rühma eesti keelt korraga, kas siis tunniplaani haldamises on võimalik rühmasid eristada. Helen katsetab. 
Kui tahad õpetaja kaupa planeerida, siis kuidas see teha.
Kui meil on 100 õpetajat, siis kuidas kuvatakse - see oli kõrghariduses teema. 

Arutame koosolekul.

**Comment by irinakelder** [comment]
Teha valitud planeeritav rühm rohkem nähtavaks, lisada nt "Planeeritavad tunnid" juurde "rühm XXX"

**Comment by Helenvaltmann** [comment]
kooli informeeritud

**Comment by Lendaja** [comment]
tehtud ver 0.5

**Comment by Pirgit** [comment]
II etapis lisada õpetaja kaupa tunniplaani haldamise vaade.

**Comment by AnuPiirisild** [comment]
"lisada õpetaja kaupa tunniplaani haldamise vaade" _tõstetud Jira'sse: TAHVEL-54_
