### ISSUE TITLE
Mooduli lisamise probleem

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#14]
Lisan kooli poolse kommentaari, peaks mõtlema, kas saab kuidagi lahendada seda:

Mooduli lisamine – mooduli lisamiseks avaneb eraldi aknake, aga kui liikuda hiirega sellelt aknalt ära ja teha klõps (näiteks kerimisribal  taustal oleva lehe serval, või eksib käsi, kui on soov kasutada kerimisnuppu selle sama mooduli sisestamise akna serval), siis kaob mooduli sisestamise aknake eest ära ja kogu seni kirjutatud info on kadunud. Sama kehtib ka mooduli rakenduskava lisamise kohta. Kuna moodulite ja rakenduskavade sisestamine nõuab palju copy-paste tegevust, st. liikumist eri akende vahel, siis on suhteliselt tülikas, kui näpuvea tõttu tehtud töö kaduma läheb. Kui selle vältimiseks vahepeal mooduli või rakenduskava andmeid salvestada, siis salvestamisega läheb aknake kinni , töö jätkamiseks tuleb uuesti aknake avada, see on samuti suhteliselt tülikas.

**Comment by irinakelder** [comment]
Teeme, et aken kinni ei läheks

**Comment by Lendaja** [comment]
Tehtud (v 0.3.0).

**Comment by Helenvaltmann** [comment]
korras, aitäh, panen kinni
