### ISSUE TITLE
Tunniplaani haldamine - päevade kuvamine - soov on saada vaade selgemaks (Pärnumaa)

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#140]
•	Praegu on tunniplaani tegemisel kõik tunnid-päevad ühes jorus, päevad võiks ikka mingi joonega eraldatud olla, muidu ei pane tähelegi, kas lisad tundi esmaspäeva lõppu või teisipäeva algusesse.

**Comment by Helenvaltmann** [comment]
see ei ole hetkel prioriteetne. saame probleemist aru, eriti kui on palju rühmi, kellele korraga tunde tõmmatakse.

**Comment by Helenvaltmann** [comment]
Koolile vastatud

**Comment by AnuPiirisild** [comment]
_Tõstetud Jirasse: TAHVEL-53_
