### ISSUE TITLE
H&F Andmete ületoomine eKoolist - Fujitsult nõu küsida

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#142]
Palun arutame seda teemat ka koos kolmapäeval 1. novembril.
/Helen

Tere!

eKoolis on kõik koolid samas andmebaasis. Mille struktuur on suhteliselt keeruline. Andmebaasi dumpi, mis sisaldaks vaid Teie küsitud koolide andmed ning mis oleks kuhugi sisse loetav - arvan, et sellise koostamine on piisavalt keeruline ja aeganõudev ülesanne. Lisaks - mõlemad koolid on eKooli kasutajad juba väga kaua aega olnud (mõlemad aastast 2006), kas Teil on tõesti vaja kogu ajalugu endale saada? 

Ja siin on veel üks konks - andmeid 2001 - 2010 olid vanas andmebaasis ja pikemat säilitamist vajav info (inimesed ja kokkuvõtvad hinded ning päevikute html failid) migreeriti uude baasi 2010. Vana baasi halduseks puudub meil võimalus (Oracle mootor ja server, kus kõik see tööle saada ning ka teadmised, kuidas see toimis, sest inimesed on vahetunud). 

Seega palun ikkagi läbi mõelda, millist infot Teil vaja on: inimesi, hindeid, hinnete kommentaare, õppekavasid ja ainekaarte, tunnikirjeldusi, koduseid ülesandeid, vestlusi, märkusi, teateid, õpilaste esitatud ülesannete faile, töökavasid, materjalide faile, vanemate-laste suhteid, sündmusi, blogisissekandeid, hindeskeeme, tunniplaane... need on asjad, mis just hetkel meelde tulid. Ja mida nendest on ÕIS2 võimeline koolidele loetaval kujul esitama ja mis jääbad bitikogumikuks. 

Ja veel - lisatöö (protsessi koostamine ÕIS2 jaoks andmete dumbi koostamiseks) eeldab lisafinantseerimist. 

Lugupidamisega,

Ene Lindemann

-----Original message-----
From: Helen Valtmann-Valdson <Helen.Valtmann-Valdson@hitsa.ee>
Sent: 10/19/2017 15:49:31

> Tere!
> 
> Suur tänu kiire vastuse eest!
> Meil on vaja täisandmete dumpi ehk andmebaasikoopiat.
> Palun öelge kas ja mis tingimustel see on võimalik?
> 
> Lugupidamisega,
> 
> Helen Valtmann-Valdson
> IT projektijuht-analüütik
> Helen.Valtmann-Valdson@hitsa.ee
> +372 6285886
> 
>

**Comment by irinakelder** [comment]
1) Tuleb küsida xml-id (õppesooritused, inimesed)
2) Õppekavad jms sisestatakse otse ÕISi, nt teisse keskkonda ja pärast tuuakse live'i üle skriptia

**Comment by Helenvaltmann** [comment]
kirjutasin eKooli esindajale küsimuse

**Comment by Helenvaltmann** [comment]
eKool vastas:
koolid saavad ise võtta välja oma kokkuvõtvate hinnete xml ekspordi faili. Faili struktuur on kirjeldatud: 

https://wiki.ekool.eu/index.php/Hinnete_eksport

**Comment by Helenvaltmann** [comment]
koolidelt vaja kiiremas korras eksport küsida.

**Comment by Pirgit** [comment]
Esimene kool on üle kantud ning info on olemas.
