### ISSUE TITLE
Tunnijaotusplaani ja päeviku lisamise vormi täiendused (kohtumiselt 1.11.17)

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#143]
Irina, ma tegin selle ka piletiks, mis sa mailis eraldi kirja panid:)

1)	Tunnijaotusplaani juures kui kokku numbrid ei klapi, siis tuleb vastavad numbrid teha punaseks (hetkel arendaja keskkonnas läheb taust punaseks, aga võiks olla tekst)
2)	Päeviku lisamise vormil muuta disain – hindamisviis ja osakaal tõsta vasakule ja õppetööliigid tõsta paremale(kuna need pole nii olulised), õppetöö liikide juurde sulgudesse lisada sõltuvalt valitud teemast vastavad mahujaotuste numbrid

**Comment by Pirgit** [comment]
see on teostatud.
