### ISSUE TITLE
Statistika näited abiks ÕIS2 statistika/päringute tegemisel (Pärnumaa Kutsehariduskeskus)

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#144]
[Statistika.docx](https://github.com/hariduspilv/oppeinfo/files/1454249/Statistika.docx)

Tere

Saadan Teile Pärnumaa Kutsehariduskeskuse õppeinfosüsteemi statistika osa näite.

Lugupidamisega
Helke Heinmets
õppe- ja tugiteenistuse juhataja

Pärnumaa Kutsehariduskeskus
kab A002
(+372) 5137388, 
(+372) 4447195
helke.heinmets@hariduskeskus.ee

**Comment by AnuPiirisild** [comment]
Tõstetud arendusettepanekutesse (vajab eelnevalt võrdlemist).
