### ISSUE TITLE
Stipendumitaotlus - faili lisamise võimalus

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#146]
EBS kirjutas, et stipendiumitaotlusele on vaja juurde faili(de) lisamise võimalust. Vaatasin, et õppetoetustel on see olemas aga stipendiumite all ei hakanud silma. Palun lisada taotlustele faili lisamise võimalus. Kui on plaanis juba olemas, siis on  hästi:)

**Comment by irinakelder** [comment]
lisame

**Comment by Helenvaltmann** [comment]
aitäh!:)

**Comment by Lendaja** [comment]
ver 0.6.0
