### ISSUE TITLE
Kutseõppe õppekavas ei ole alati valikmoodulit

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#15]
Kuigi analüüsis on kirjas, et valikmoodul peab alati olema - andis Järvamaa Kutsehariduskeskus teada, et neil on ka õppekava, kus ei ole valikõpingute moodulit. Näiteks Teetöömasinate juht

Seega oleks vaja reegel "vähemalt üks valikmoodul" eemaldada.

**Comment by Pirgit** [comment]
28.09.16 koosoleku kokkuvõttest leidsin ka selle info, et valikmoodulit ei pea olema.

**Comment by irinakelder** [comment]
Eemaldame

**Comment by Lendaja** [comment]
Tehtud (v 0.3.0).

**Comment by Helenvaltmann** [comment]
toimib, kinni, aitäh
