### ISSUE TITLE
Tunniplaani tagasiside (TKTK) 

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#152]
saadetud meile 5.12.17

Tere!

Proovisin pärast meie 24. oktoobri testimishommikupoolikut tunniplaani sisestamist. Jäin hätta, sest andmeid on sisestatud liiga vähe kõikide variantide proovimiseks. Katsetasin andmeid ise sisestada, aga vaja oli liiga palju eriteadmisi ja jätsin pooleli, kuna endal tuli väga kiire aeg. Praegu ei saa enam sisse.

Olen eelmise arendaja puhul juba kõik oma soovid, muudatused ja ettepanekud teinud, aga praegu panen siia kirja esmaselt pähetulevad asjad, mida tingimata vaja on.

1) Juba paigutatud tunniplokke peab saama lohistada mujale, muuta ruumi, tunniploki pikkust. Seda nii kogu semestri osas, alates mingist tunnist edasi ja ühekordselt.

2) Tunniplokile peab saama enne paigutamist märkida järgmist: 
- eksam
- arvestus
- eksamieelne konsultatsioon
- konsultatsioon
- praktika kaitsmine
- projekti kaitsmine
- järeleksam

Koormuse koostamisel tuleb tunniplaani jaoks vaikimisi kas loeng või praktikum.

3) Tunniplokkide koostamisel peab saama lisada teisi rühmi, teise(d) õppejõu(d). Kui õppejõul on koormuses mitu rühma, peab saama neid linnukesega ära jätta.

4) Peab saama validatundide sageduse (iga nädal, iga päev, ühekordne, üle nädala jne.)

5) Peab saama panna mitu tundi ühele ajale, ühte ruumi, ühele õppejõule. ÕIS peab hoiatama.

Praegu ei meenu muud. Testida saab siis, kui õppekavu, õppejõudusid, rühmi, koormusi on juba piisaval hulgal olemas.

Tänu ja kena advendiaega!

Maria Laurson
Tallinna Tehnikakõrgkooli õppekorralduse spetsialist
6664519

**Comment by AnuPiirisild** [comment]
Tõstetud arendusettepanekutesse punktid 1, 2.
Tahvlis funktsionaalsused juba olemas punktid 3, 4.
Versioonis 1.0.0. kõrg poolel punkt 5 hoiatus veel ei toimi (kutse poolel olemas). Läheb veana üles.
