### ISSUE TITLE
Lõpetamine - Lõputöö teemad - klikkimisel Süsteemi viga

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#154]
Kui võtta lõpetamine ja lõputöö teemad, siis teatab Süsteemi viga. Kui andmeid menüü all 
![e4c8e58880562695ba15f7b95b8e168e85fbe1cd578a633d21 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/26483158/34300504-183d1426-e731-11e7-97df-e479efef106c.png)
 ei ole, siis üldjuhul ütleb programm Otsingule vastavaid kirjeid ei leitud.

Süsteemi viga tuleb lisaks veel ka teistel Lõpetamine menüü alamteemadel - pilt on lisatud alamteemade kohta, mille puhul ilmub süsteemi viga teade.

**Comment by Helenvaltmann** [comment]
Lõpetamine menüü all on nüüd Lõpudokumentide trükkimine. Varasemalt olid seal pildil nähtavad menüüd. Kas need lisatakse sinna hiljem uuesti, sest ma ei leidnud neid hetkel teiste menüüde alt?

**Comment by AnuPiirisild** [comment]
Lõpudokumentide osa on täiendatud.
