### ISSUE TITLE
Kasutajaõigused -Kasutajale saab lisada ühe kooli lõikes sama rolli mitu korda

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#155]
Kasutajad -valin kasutaja - Kasutajarollid - Lisa uus - samale kasutajale, samas koolis saab lisada topelt rolli.
Näide: Helen Valtmann-Valdson, TKTK - administratiivne töötaja, administratiivne töötaja.

ps. ma ei tea kas sellest tuleb probleemi  - mis juhtub kui ühel kasutajarollil on rohkem õigusi kui teisel.
pildid lisatud.

Samas kasutaja peaks saama samas koolis olla nii administratiivse töötaja kui õpetaja rollis.
![testtahvel1](https://user-images.githubusercontent.com/26483158/34521008-1c1b0d2a-f094-11e7-8bb8-df0cc3fbdbff.png)
![testtahvel2](https://user-images.githubusercontent.com/26483158/34521009-1ea8f052-f094-11e7-84e5-fbf145f4dac8.png)

**Comment by Lendaja** [comment]
Kui kogemata on lisatud sama nimega roll, siis on see kohe näha ja saab kustutada.
