### ISSUE TITLE
Mobiil-ID-ga sisselogimine - mobiili numbri salvestamise võimalus

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#158]
Kui Mobiil-ID-ga sisse logida pidevalt ühest brauserist, siis võiks olla võimalus (valikuvariant) salvestada mobiili number. Võibolla on see hoopis brauseriga seotud teema aga mina sellist varianti ei ole leidnud, et saaks salvestada.

**Comment by erkkijakobson** [comment]
Funktsionaalsus sõltub brauserist ja selle seadetest, Chromega (topeltklikk) näiteks töötab kenasti:
![image](https://user-images.githubusercontent.com/16906555/34569143-84f6b5b0-f170-11e7-8c90-6e26ae831074.png)

**Comment by Helenvaltmann** [comment]
aitäh! uurin siis mis võiks Chrome'i puhul see nupp või kombinatsioon olla:)

**Comment by erkkijakobson** [comment]
Chrome kolme täpi menüü > Seaded > Täpsemad > Paroolid ja vormid > Automaatse täitmise seaded:
kui lüliti on sees, jätab Chrome korra läbi vormi esitatu meelde, mille toob nähtavale topeltklikk vormil.

Tüüpiliselt peab e-teenus vaeva nägema, et see ei toimiks - näiteks enamik panku on selle keelanud.

**Comment by Helenvaltmann** [comment]
Suur tänu Erkki! Mõtlesin ka ise googeldada aga läks juba meelest. Sellest on väga kasu meile endile ja edaspidi ka kasutajatele:)
