### ISSUE TITLE
Mahtude kontroll

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#16]
Kooli tagasiside: 
Mooduli  andmetes rakenduskavas ei ole kontrolli EKAP-ite arvu ja sisestatud tundide jaotuse vahel. 
Puudub ka kontrollmehhanism, et sisestatud tundide maht eri õppetöö liikide juurdes klapiks mahu jaotusega õppeaastate lõikes.

Minu küsimus: Millised kontrollid mahtude osas I etapis teostatakse?

**Comment by irinakelder** [comment]
Kontrollime moodulite EAP/EKAP ja õppekava mahu vastavust, kontrollid on analüüsis kirjas.
RAkenduskava EKAPi ja tundide vastavuse kontrolli ei ole ja I etapis ei tule
