### ISSUE TITLE
Õppekava - Kooli õppekava- sisestaja ja muutja andmed - kuvab nime asemel isikukoodi

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#160]
Kui võtta kooli õppekava, siis kuvab Sisestaja/muutja ees- ja perekonnanimi all isikukoode.
Riiklikus õppekavas kuvab ees-ja perekonnanime.
Pilt lisatud.
![kooliok](https://user-images.githubusercontent.com/26483158/34714884-7eea609c-f533-11e7-8936-96c94fcd2281.png)

**Comment by Lendaja** [comment]
Tehtud ver 0.6.2
