### ISSUE TITLE
Vastuvõtt- vastuvõtu avaldused - lisada valesti imporditud avalduse eemaldamise võimalus

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#161]
Lisada programmi valesti CSV-ga imporditud avalduse kustutamise võimalus.
Lisatud peab olema võimalus eemaldada avaldusi ühe ja mitme kaupa, nii nagu on praegu ÕIS1-s

**Comment by AnuPiirisild** [comment]
Tehtud
