### ISSUE TITLE
Riiklikud õppekavad - sisestamine - Salvestamine - Moodulid

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#162]
Lisada riiklikusse õppekavasse sarnaselt kooli õppekavaga see võimalus, et sisestaja ei pea enne üldandmete sisestamise lõpetamist salvesta vajutama, vaid võib hakata ka mooduleid koheselt sisestama.
Praegu on mitmel sisestajal juhtunud see, et tehakse mitu tundi tööd ja kui tuleb süsteemi/sessioon aegub, siis läheb töö kaduma.

**Comment by AnuPiirisild** [comment]
Vajadust vaja analüüsida.
