### ISSUE TITLE
Riiklikud õppekavad - Moodulite kopeerimise võimalus

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#163]
Palun lisada programmi Moodulite kopeerimise võimalus. Hetkel sisestame kõikidele riiklikele õppekavadele üldõpingute mooduleid (7 tükki) uuesti ja uuesti. See võtab aega orienteeruvalt 1 tund. Sõltub muidugi ka sisestaja kogemusest.

**Comment by Pirgit** [comment]
Üldõpingute moodulite puhul ka kooli õppekavas on esitatud soov neid keskselt sisestada ja muuta. II etapis tuleb soov detailselt kirjaldada.

**Comment by AnuPiirisild** [comment]
_Tõstetud Jira'sse: TAHVEL-52_
