### ISSUE TITLE
Riiklikud õppekavad - kutse lisamise väli muuta rohkem arusaadavamaks, et tegu on sisestuse väljaga

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#165]
Väli, Lisa kutse näeb teistsugune välja ja uus kasutaja ei saa aru, et tegu on sisestamise väljaga. Lisatud pilt Kutse1
![kutse1](https://user-images.githubusercontent.com/26483158/35433933-e2b7cb16-028d-11e8-8883-11cdfaf41ae7.png)
Kui kutse on lisatud, peab see sisestusväljalt ära kaduma. Lisatud pilt Kutse2

**Comment by Helenvaltmann** [comment]
![kutse2](https://user-images.githubusercontent.com/26483158/35433951-f815137e-028d-11e8-9034-7bc80b0aefcb.png)

**Comment by Pirgit** [comment]
Kooli õppekaval on nupuna, riiklikul ei ole.
