### ISSUE TITLE
Riiklikud õppekavad - osakutset ja spetsialiseerumist ei saa korraga riiklikule õppekavale määrata

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#166]
Riiklikul õppekaval on vaja määrata korraga nii osakutse kui ka spetsialiseerumine. 
Näiteks toon tahvel.edu.ee riikliku õppekava nimega Põllumajandustöötaja.

Riigi Teataja paragrahv 7 järgi on vaja  määrata Põhiõpingute moodul nr11 ni spetsialiseerumisele kui osakutsele. 
https://www.riigiteataja.ee/akt/102032017011 

Antud näites „Veisekasvataja, tase 4“ spetsialiseerumine; „Lamba- ja kitsekasvataja, tase 4“ spetsialiseerumine; ja osakutsele „Lüpsja, tase 4“ vastavad kompetentsid.
Veateade on järgnev: Moodul ei saa olla seotud ühe kutse spetsialiseerumise ja osakutsega 
Palun muuta nii, et osakutse ja spetsialiseerumise saaks korraga valida(linnutada)

**Comment by AnuPiirisild** [comment]
_Tõstetud Jira'sse: TAHVEL-51_
