### ISSUE TITLE
Riiklikust õppekavast kooli õppekava koostamine. Mooduli õpiväljundid on vales järjekorras.

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#168]
Kui luua Riiklikust õppekavast kooli õppekava, siis on Riiklikus õppekavas toodud mooduli õpiväljundite järjekord sassis.
Näide - test.tahvel.eenet.ee - kool TPT
Riiklik õppekava nimega Kokk
Võtan kooli õppekava loomise ja aluseks Koka riikliku õppekava.
Lisatud pilt  Riikliku õppekva moodulist ja pilt 
![kooli oppekava moodul](https://user-images.githubusercontent.com/26483158/35564964-7baf71e6-05c4-11e8-9d35-ad31df3489a1.png)
![rokmoodul](https://user-images.githubusercontent.com/26483158/35564965-7bd3d9b4-05c4-11e8-9b70-1b95d9e6903e.png)
 Kooli kokka õppekava moodulist.
Noolekestega saab küll järjekorda muuta aga ei ole mõeldav, et nad neid ise nüüd muutama hakkavad kui riiklikust õppekvas on algselt õiges järjekorras.

**Comment by Helenvaltmann** [comment]
sealt edasi läheb rakenduskavasse ka vale järjekorraga.

**Comment by esterpae** [comment]
Kui kooli õppekavas õv järjekorrad noolekestest õigeks panna, siis mooduli teemas õv valimisel on järjekord ikkagi sassis.

**Comment by Pirgit** [comment]
Anu palun kontrolli üle, kas hetkel viga eksisteerib.

**Comment by AnuPiirisild** [comment]
Korras. Testitud versioonis 0.6.9.
