### ISSUE TITLE
Kooli rakenduskava Mooduli teema sisestamisel ei saa sisestada mahuks tunde

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#169]
Kooli rakenduskava sisestamisel ei saa Mooduli teema sisestamisel sisestada teema mahtu  tundides.
![teemamaht](https://user-images.githubusercontent.com/26483158/35569022-8853fb9c-05d3-11e8-81ba-dc9f87767a22.png)

Katsetatud testbaasis TPT koolis. Teade: 
arv peab olema sisestatud täpsusega üks koht peale koma.
Pilt lisatud

**Comment by Lendaja** [comment]
tehtud ver 0.6.3

**Comment by Helenvaltmann** [comment]
töötab, aitäh
