### ISSUE TITLE
Mooduli/teema/ainete mahu jaotus kooli põhiselt. 

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#17]
Pole aru saada, kas „loeng“ ja „praktiline töö“ kuuluvad auditoorse õppe hulka, või on need lisaks. Loengut ei oleks kutseõppe puhul üldse vaja. Auditoorne õpe võiks jaguneda teoreetiliseks tööks ja praktiliseks tööks. Lisaks iseseisev töö ja vaja oleks ka e-õpet ning kindlasti praktikat, sest osa mooduleid sisaldavad praktikat.

**Comment by irinakelder** [comment]
Klassifikaatori juures praegu saab seadistada kas kuvatakse kutse või kõrg õppes, sellega saab valikud I etapis enam-vähem korrektseks. Muud asjad II etapis
