### ISSUE TITLE
Õpiväljundite loetelu mooduli teemade lisamise vaates

### ISSUE THREAD

**Issue by esterpae** [hariduspilv/oppeinfo#170]
Testkeskkond - admin töötaja

Kooli õppekavad - moodulite rakenduskavad - Vaata mooduli andmeid - teema
![opivaljundite vali mooduli teema lisamise vaates](https://user-images.githubusercontent.com/35957296/35569813-e73ad994-05d5-11e8-9136-5c31924f4cbb.png)
 (lisamine) - 
https://test.tahvel.eenet.ee/?#/occupationModule/12/4/226/50/edit

Väli "seos õppeväljundiga":
1) Asendada mõiste "õppeväljund" mõistega "õpiväljund",
2) Kas on võimalik reastada valitud õpiväljundid üksteise alla ja väli pikkuses suuremaks muuta? Praegu on väljundid üksteise järel reas ja kaovad vaateväljast.

**Comment by esterpae** [comment]
Lisaks: konkreetses õpiväljundiga seose loomise (õv valimise) kohas on õpiväljundite järjekord paigast ära!

**Comment by AnuPiirisild** [comment]
Asendada mõiste "õppeväljund" mõistega "õpiväljund" - tehtud

**Comment by AnuPiirisild** [comment]
Kas eraldi ridadele kuvamine on vajalik? Seda näeb ÕK teemasid vaadates ka avalikus vaates. Seos piletiga Jira's Tahvel-50.
Järjekord on paigast ära siis, kui õppekava all on see segamini läinud.
