### ISSUE TITLE
Spetsialiseerumiste nummerdamine eri vaadetes erinev

### ISSUE THREAD

**Issue by esterpae** [hariduspilv/oppeinfo#171]
Test-admin töötaja

Kooli õppekava vaates ja rakenduskava vaates on spetsialiseerumiste nummerdus erinev - nt restoranitöö on ühes vaates spets nr 1 ja teises vaates spets nr 2:
https://test.tahvel.eenet.ee/?#/vocationalCurriculum/12/view
https://test.tahvel.eenet.ee/?#/vocationalCurriculum/12/moduleImplementationPlan/4/view

![rakenduskava vormi vaade kokk](https://user-images.githubusercontent.com/35957296/35571102-da66134c-05d9-11e8-86b4-845c57bb5c4e.png)
![kooli oppekava vaade kokk](https://user-images.githubusercontent.com/35957296/35571097-d4c0b6ae-05d9-11e8-8fe8-b543426ece9d.png)

**Comment by Pirgit** [comment]
Hetkel pole probleemist koolide poolt teavitatud, kui tekib uuesti, siis avame.
