### ISSUE TITLE
Riiklikust õppekavast kooli õppekava loomine - üldõpingud, põhiõpingud

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#172]
Riiklikus õppekvas on järjestus üldõpingud, siis põhiõpingud.
Kui Riiklikust kooli õppekava koostada, on järjekord põhiõpingud, üldõpingud. 
Kui oligi nii plaanis, siis las olla. Kui ei, siis kunagi ümber tõsta. Sealt edasi on rakenduskavas ka üldõpingud peale põhiõpinguid.
![koolioppekava](https://user-images.githubusercontent.com/26483158/35612910-02522064-0673-11e8-8462-612a727bf6b8.png)

Pilt lisatud

**Comment by Pirgit** [comment]
Järjekord kooli jaoks on: põhiõpingud, üldõpingud, valikõpingud. Seega nii sobib.
