### ISSUE TITLE
Kooli õppekava - spetsialiseerumised - valikõpingud, põhiõpingud - arutada, mis ja kuidas teha, sisetada

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#173]
Helen,

mis sa välja pakud?

Koka kooli õppekava kaudu oli võimalik spets moodulid panna valikõpingute alla, tegin seda:
https://test.tahvel.eenet.ee/?#/vocationalCurriculum/12/view?_menu

RÕKis on põhiõpingud, seal ei saa valida.

Kui spetsialiseerumine on valikõpingute all (nii nagu RÕK antud juhul ette näeb), siis ei saa menetleda õppekava, sest annab punast: "Igale kutsele/osakutsele/spetsialiseerumisele peab olema lisatud vähemalt 1 põhiõpingute moodul". Antud juhul on teist lahendust vaja ...

Ester

**Comment by AnuPiirisild** [comment]
Oleme leidnud lahenduse.
