### ISSUE TITLE
Kutseõppetunnijaotusplaan - Kui õppetöö liik on puudu, tuleb teade inglise keeles

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#174]
Vaja eesti keelde tõlkida
Pilt lisatud
![oppetoo liik](https://user-images.githubusercontent.com/26483158/35615214-259f0ecc-067a-11e8-9056-f6e2f02cecac.png)

**Comment by Helenvaltmann** [comment]
Teema puhul sama asi, et teade on inglise keeles.
![teema puudu](https://user-images.githubusercontent.com/26483158/35615276-59e53d5a-067a-11e8-8342-31ac1b21ae9f.png)
 Pilt lisatud

**Comment by AnuPiirisild** [comment]
Tehtud
