### ISSUE TITLE
Rakenduskava mooduli mahtude jaotuse õppeaastate arv

### ISSUE THREAD

**Issue by esterpae** [hariduspilv/oppeinfo#176]
Rakenduskava mooduli mahtude jaotus ja teema õppeaastate valik on fikseeritud 3 õppeaasta peale, sõltumata õppekava kestvusest. Pikemate kui 3 a 0 kuud õppekavade puhul on vaja valikusse saada rohkem kui 3 aastat (nt 4 aastat 3 a 6 k õppekava puhul); 2 a 0 k puhul on õppeaastate valikus piisav 2 aastat, 1 a 0 k puhul 1 aasta. 
Parim oodatav tulemus: õppeaastate valik on kohanduv õppeaja kestvusega (väli kooli õppekava põhiandmetes).
Minimaalne vajadus: valikus on 4 õppeaastat.

![mooduli mahud oa loikes](https://user-images.githubusercontent.com/35957296/36212911-e1ad10bc-11ad-11e8-924a-c43723c49618.png)

![mooduli teema lisamisel oa valik](https://user-images.githubusercontent.com/35957296/36212922-e816e81a-11ad-11e8-9181-0785f91481c1.png)

Administratiivne töötaja, Google Chrome.

**Comment by Pirgit** [comment]
Hetkel teeme juurde 4. õppeaasta. Nii teemade vaatesse, kui mooduli mahu jaotusesse.

**Comment by Lendaja** [comment]
tehtud v 0.6.5

**Comment by AnuPiirisild** [comment]
Endiselt näitab kuni 3
![image](https://user-images.githubusercontent.com/36628933/37830191-5ae3f144-2eaa-11e8-98bd-a0e71bd71493.png)

**Comment by Lendaja** [comment]
Palun näidet (kool, õppekava), kus näitab aastaid valesti.

**Comment by AnuPiirisild** [comment]
Töötab, aitäh.
