### ISSUE TITLE
Töökohapõhise õppe mahtude jaotus

### ISSUE THREAD

**Issue by esterpae** [hariduspilv/oppeinfo#177]
Detailanalüüs ütleb, et töökohapõhise õppe puhul saab mooduli mahtude jaotuses eristada koolis toimuva ja töökohal toimuva õppe mahtusid, kuid see ei tööta.
Töökohapõhisele õppevormile loodud rakenduskava mooduli andmete lehele kirjeldatud jaotisi ei teki.

![tookohapohise oppe mahtude jaotus](https://user-images.githubusercontent.com/35957296/36213908-a0d6cf58-11b0-11e8-817b-cb80a37ec450.png)

![tookohapohise oppe mahtude jaotus 2](https://user-images.githubusercontent.com/35957296/36214654-b950a250-11b2-11e8-8a69-11c443a0e62b.png)

**Comment by Lendaja** [comment]
Küsimus saadetud Pirgitile 16.02.18

**Comment by AnuPiirisild** [comment]
Kui rakenduskavale on märgitud töökohapõhine õpe, siis mooduli mahu jaotuses peaks kuvama ka töökohal läbitud õppe infot.
Saan klassifikaatorite alt peaadministraatorina lisada, kuid siis kuvab ka teistes õppevormides. Kui see on sobiv, siis lisan.
