### ISSUE TITLE
Moodulite järjekord riikliku õppekava trükifailis ei vasta veebivaate järjekorrale

### ISSUE THREAD

**Issue by esterpae** [hariduspilv/oppeinfo#178]
Peaaadministraator - https://tahvel.edu.ee

Riikliku õppekava trükifaili moodulite järjekord ei vasta riikliku õppekava moodulite veebivaate järjekorrale. Veebivaates on järjekord: 1) Üldõpingud, 2) Põhiõpingud; moodulid paigutatakse numereerimise järjekorda sõltumata sisestusjärjekorrast.

Kas trükifaili moodulite järjekord võib olla sõltuvuses moodulite sisestusjärjekorrast või on põhjus mujal? RÕK näited:
Kujundaja - Põhiõpingud - Üldõpingud
Florist - Üldõpingud - Põhiõpingud 
IT-süsteemide nooremspetsialist - Üldõpingud - Põhiõpingud - Üldõpingud

![rok ainete jarjekord veebis](https://user-images.githubusercontent.com/35957296/36248590-b89c49d4-1240-11e8-8403-fc413a32071d.png)

![rok ainete jarjekord prindifailis](https://user-images.githubusercontent.com/35957296/36248602-bfb5991e-1240-11e8-9935-d0a65ae21a6d.png)

**Comment by esterpae** [comment]
Õpiväljundite järjekorrad on ka trükifailis osadel moodulitel paigast ära, vales järjekorras - erinevad veebivaate ÕV järjekorrast.

**Comment by AnuPiirisild** [comment]
Trükifailis võtab sisestatud moodulite järjekorra, kuid tekitab omakorda oma mooduli üldjärjekorra.
![image](https://user-images.githubusercontent.com/36628933/37829435-a34e0fb2-2ea7-11e8-9549-930a0a9d6ca4.png)

**Comment by Pirgit** [comment]
Palun kontrolli üle ning see tuleks I etapis lahendada.

**Comment by AnuPiirisild** [comment]
Moodulid on veebis ja trükifaili vaates samas jrk. Kuid moodulite kirjelduste juures on õpiväljundid segamini järjekorras. Näiteks HAK ÕK Aednik, moodul _01. Keel ja kirjandus_:
![image](https://user-images.githubusercontent.com/36628933/39625854-162c94c4-4fa8-11e8-9152-dd6246097154.png)
Veeebivaates on need õpiväljundid õiges järjekorras.

**Comment by AnuPiirisild** [comment]
Verisoonis _1.0.0_ kuvab veebivaates õpiväljundeid segamini, kuid kui noolekestega ära korrigeerida, siis on trükifailis õige jrk.
