### ISSUE TITLE
Rakenduskavad

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#18]
1. teemade sisestamine – kohustuslik on lisada maht EKAP-ites ja tundides, kui sisestada EKAP-ite arv, siis arvutatakse automaatselt välja vastav tundide arv, aga võiks olla ka nii, et kui sisestada tundide arv, arvutataks selle põhjal EKAP-ite arv.  
2. Samas võimaldab testkeskkond lisada tundide arvu nii, et see ei ole seotud EKAP-ite arvuga, siin peaks ikkagi mingi kontroll olema. 
3. Teema mahu jaotus ei anna tagasisidet, kui teema jaoks ettenähtud tundide arv on väiksem või suurem kui eelnevalt  teema jaoks sisestatud. 
4. Teemat ei ole võimalik siduda õpiväljundiga – vastavasse valikuaknasse ei ilmu ühtki mooduli õpiväljundit. 
5. Vajalik oleks ka võimalus teemade juures tuua välja konkreetse teema iseseisva töö ülesande kirjeldus.

**Comment by irinakelder** [comment]
1. Lisame
2. Teeme range kontrolli (teema juures)
3. Vt 2
4. Viga oli
5. Tehtud Innove vormi järgi, seal teema juures puudub eraldi iseseisva töö kirjeldus. Saab sisestada kokkuvõtva hinde kujundamise väljale

**Comment by Lendaja** [comment]
Tehtud (v 0.3.0).

**Comment by Lendaja** [comment]
Tehtud punktid 1-3 (v 0.4.0)
