### ISSUE TITLE
SAISst avaldus

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#183]
Hetkel ei kuva SAISst tõmmatud avaldusel EHIS põhikooli ainete nimetusi, hinded kuvab. Aine nimetuse asemel on kirjas: EhisPohikooliAine.

Lisaks on näha, et avaldusel on lisafail aga kust ma seda avada saan? Seal on kirjas vaid: 
Lisa fail | a98ca593-365a-4e5c-8c25-073224fc257d
II kategooria mootorsõidukijuhi tervisetõend | 2f925185-cf30-4434-925a-5d20c831c934

**Comment by Lendaja** [comment]
tehtud v 0.6.5; faile ei tõmmata SAISist ÕISi, kuvatakse informatiivselt, kus fail paikneb.
