### ISSUE TITLE
Õppematerjalide (kutse) lisamine ja muutmine

### ISSUE THREAD

**Issue by esterpae** [hariduspilv/oppeinfo#184]
Õppematerjali lisamine ja muutmine ei tööta ootuspäraselt (testkeskkond: admin töötaja, õpetaja).

Õppematerjali lisamine "Lisa olemasolev" kaudu ei tööta - ei leita juba lisatud materjali, teade: vormil on vigu (nii admin töötaja kui õpetaja vaates). 

Lingiga materjali kirje MUUTMISEL (nt kui on soov materjali nimetust või kirjeldust muuta) ei ole andmeväljal "Link*" eelnevalt lisatud veebilinki enam näha ja ka salvestamisel jääb link kadunuks. 
(Failiga materjali kirjelduse või nimetuse muutmisel jääb fail alles, aga faili ennast ei saa kirje kaudu välja vahetada, vaid peab eelneva kirje kustutama ja lisama uue.) 

Admin töötaja ja õpetaja
Päeviku VAATAMISE vormil saab õppematerjale muuta (aga mitte lisada), sest SALVESTA nupp on aktiivne - nii võib kogemata midagi (nt veebilingi) ära kustutada. 
Päeviku MUUTMISE vormil pole õppematerjali üldse näha - päeviku muutmise vormilt peaks samuti õppematerjal nähtav olema. 

Kas õppematerjali muutmise ja lisamise võimalus peaks jääma aktiivseks ainult eraldi õppematerjalide menüüpunkti kaudu?

![oppematerjalide lisamine ja muutmine kutse](https://user-images.githubusercontent.com/35957296/36473751-2be7078c-16fe-11e8-8fbb-d87e85a6b81a.png)

![sisestatud oppematerjali link kaob ara](https://user-images.githubusercontent.com/35957296/36475480-747ac5d8-1703-11e8-9a3a-adb411eadd22.png)

(Õppematerjali lisamise lahendus erineb detailanalüüsis varasemalt kirjeldatust.)

**Comment by AnuPiirisild** [comment]
Täpsustan:
Õpetajana:

Õppematerjalide alt lisades lingi täisnime ei salvesta
Õppetöö ->t Õppematerjalid (kutse)
![image](https://user-images.githubusercontent.com/36628933/37826852-cc7d1144-2e9d-11e8-89fa-22530d6e7f8a.png)
Ka teistes vaadetes ei näita täislinki.

Päevikus lisades salvestab ja kuvab korrektselt
Õppetöö -> Päevikud (kutse)
![image](https://user-images.githubusercontent.com/36628933/37827012-5f47ebe8-2e9e-11e8-90ea-8b6fe3b9079d.png)

Kui uuesti päeviku alt õppematerjali avan, on veebilink tühi
![image](https://user-images.githubusercontent.com/36628933/37827546-95bc1878-2ea0-11e8-935d-9927447a229c.png)

Salvestades salvestabki tühjana
![image](https://user-images.githubusercontent.com/36628933/37827570-b727a5ae-2ea0-11e8-9d49-9d30e0485984.png)


Vaja oleks juhendit, et mõisteid selgitada (tuginedes Estri kommentaarile):
"Lisa olemasolev" - töötab, kuid mõeldud varem õpetaja poolt kusagile mujale lisatud materjali leidmiseks ja lisamiseks.
Faili muutmine - täitsa ok, et vana faili kustutad. 

_Päeviku MUUTMISE vormil pole õppematerjali üldse näha_ - on näha ja saab lisada/muuta.

**Comment by Lendaja** [comment]
Ei saa korrata test tahvel kekkonnas "Õppematerjalide alt lisades lingi täisnime ei salvesta" (admin HITSA, päevik iluk, õppematerjal veebiehitamine.

**Comment by Lendaja** [comment]
lingi kuvamine parandatud ver 0.6.9
