### ISSUE TITLE
Automaatsete teadete mallide lisamine - veateade Sisu lisamisel - Tallinna Tööstushariduskeskus

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#185]
Kool ei saa lisada kolme järgnevat automaatset teadete malli: 
1.	Akadeemilise puhkuse lõppemise teade
2.	Õppuri tunniplaanis on toimunud muudatus
3.	Kasutaja on saanud õppeaines tulemuse

Sisu lisamisel 
Õppuri- ees- ja perekonnanimi: #{oppuri_nimi}
Õppuri isikukood: #{oppuri_isikukood}

teatab programm messageTemplate.invalidcontent content (pilt lisatud)
![teade1](https://user-images.githubusercontent.com/26483158/36587636-69b2e52c-188e-11e8-95c7-f99219482ea2.png)

Kordasin sama asja nende baasis. Kopeerisn ees- ja perekonnanime automaatteatelt, mis oli koolil õnnestunud salvetada. 
Sama asi on korratav ka testbaasis.

**Comment by Lendaja** [comment]
tehtud ver 0.6.6

**Comment by Helenvaltmann** [comment]
toimib, aitäh!
