### ISSUE TITLE
Päeviku sissekande kuvamisel päis peidetud

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#186]
Uue päeviku sissekande tegemisel on päis peidetud, st aken avaneb alustades alt vaatest (kui ei mahu täispikkuses ekraanile ära). 
![image](https://user-images.githubusercontent.com/36628933/37272677-12e895c0-25e0-11e8-8c3a-367968d847ae.png)

Administratiivne töötaja HITSA vaade: https://test.tahvel.eenet.ee/#/journal/16/edit
Peaks algama ülevalt.

**Comment by Lendaja** [comment]
tehtud 0.6.7

**Comment by AnuPiirisild** [comment]
Tehtud
