### ISSUE TITLE
Teated. Õpetaja vaates ümbriku ikoonile klikates teade "Vajalikud õigused puuduvad"

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#187]
Õpetaja vaates kui klikata ümbriku ikoonile, tuleb  "Vajalikud õigused puuduvad":
![image](https://user-images.githubusercontent.com/36628933/37289216-d146ec20-2611-11e8-920f-54ae23434f9c.png)

Näen neid teateid esilehe teadete ribal:
![image](https://user-images.githubusercontent.com/36628933/37289361-31fbd01c-2612-11e8-8e2c-85d7fd926a55.png)

Ei tule tavapärast saabunud ja saadetud teadete kuva.
![image](https://user-images.githubusercontent.com/36628933/37289528-8b4d8336-2612-11e8-9966-a94288d63cff.png)

Õpetaja hetkel ise teateid saata ei saa ja ma ei saa testida, kas rühmateated toimivad.

**Comment by Lendaja** [comment]
tehtud 0.6.7 (lisa skript)

**Comment by AnuPiirisild** [comment]
Tehtud
