### ISSUE TITLE
Tunnijaotusplaani päis et hanguks

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#188]
Tunnijaotusplaani täites lehel navigeerides ja lahterid täites et ülemine päis jääks nähtavale. Võimalusel samuti ka vasakpoolne info.
https://tahvel.edu.ee/#/lessonplans/vocational/228/edit
![image](https://user-images.githubusercontent.com/36628933/37756520-787f7ffa-2db2-11e8-9047-4ed8b9d0c96f.png)

**Comment by Lendaja** [comment]
Tunnijaotusplaani päise külmutamise kohta on ka pilet 117.

**Comment by Lendaja** [comment]
tehtud ver 0.6.8

**Comment by AnuPiirisild** [comment]
Tehtud
