### ISSUE TITLE
Kõigi rühmade kuvamine peale üksiktunni tunniplaani tõstmist

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#189]
Iga kord peale üksiku tunni paikapanekut kuvab (valib) kõik rühmad uuesti (uuendab kogu lehekülge). Tunniplaani koostajale on see müra ning ajakulu (igakordne lehe laadimine). 
Versioon 0.6.6/20180309
Ühe kooli näide:
![image](https://user-images.githubusercontent.com/36628933/37891609-85bfd6be-30dd-11e8-93a8-93bda528a0ae.png)

**Comment by Lendaja** [comment]
tehtud 0.6.7

**Comment by AnuPiirisild** [comment]
Tehtud
