### ISSUE TITLE
Rakenduskavas õpiväljundite hindamine

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#19]
Kooli kommentaar:
Rakenduskavades puudub võimalus tuua välja, kuidas hinnatakse õpiväljundeid, on ainult võimalus tuua välja, kuidas hinnatakse moodulit ja kuidas hinnatakse teemasid.

Sooviks arutada, kuidas seda lahendada.

**Comment by irinakelder** [comment]
Õpiväljundi hindamiseks teed teema ja seod teema ainult ühe õpiväljundiga
