### ISSUE TITLE
Õpetaja andmete sisestamisel jääb otsima

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#191]
https://tahvel.edu.ee/#/teachers/new
Lisades uue õpetaja, siis nii TAB klahvi kui hiirega juba sisestatud ees- või perekonnanimele liikudes "jääb mõttesse". Nii Chromes kui Mozillas.

**Comment by Pirgit** [comment]
Näiteks, kui kasutaja on olemas, siis küll leiab kasutaja nime aga nime väljale minnes tekib ootamise kerimine ja see jääbki. 
Samuti kui sisestan täiesti uue kasutaja, siis pannes ära õpetaja perekonnanime ja hiljem uuesti sellele minnes tekib jälle kerimine.

**Comment by Lendaja** [comment]
tehtud ver 0.6.7

**Comment by AnuPiirisild** [comment]
Tehtud
