### ISSUE TITLE
Ei saa päevikuid kinnitada

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#195]
Proovisin testis nii admin töötajana kui õpetajana päevikut kinnitada,  aga ütleb "Süsteemi viga" ja ei kinnita.

**Comment by Pirgit** [comment]
Versioon 0.6.6/20180309
Varem on saanud kinnitada. 
Kinnituse maha võtmine ei toimi testis ja live-is.

**Comment by Lendaja** [comment]
Palun andmeid, mis kool, mis päevik testtahvlis.

**Comment by Pirgit** [comment]
Näiteks testkeskkonnas HITSA kool, päevik "Pirgiti ilukirjandus"

**Comment by Lendaja** [comment]
tehtud ver 0.6.7

**Comment by AnuPiirisild** [comment]
Tehtud
