### ISSUE TITLE
VÕTA-koolide inglise keelne nimi

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#196]
VÕTA taotluses uut kooli sisestades kooli nimi inglise keeles: kõrghariduses jääks kohustuslikuks täita, kutseõppes panna mittekohustuslikuks väljaks.
![image](https://user-images.githubusercontent.com/36628933/38075479-2dc783f2-333b-11e8-9108-162d976140b2.png)

**Comment by Lendaja** [comment]
II etapi töö

**Comment by AnuPiirisild** [comment]
_Tõstetud Jira'sse: TAHVEL-48_
