### ISSUE TITLE
Negatiivsed õpitulemused kuvada punaselt

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#197]
Negatiivsed õppetöö tulemused kuvama punasena läbivalt (kindlasti punasega õpitulemuste lehel, päevikus ja moodulite protokollide koostamisel). Neg tulemused on _MA, 1, 2, X_

**Comment by Lendaja** [comment]
tehtud ver 0.6.8

**Comment by Pirgit** [comment]
Realiseeritud on päevikus kuvamine. Õpitulemustes (sooritamise järjekorras ja õppeaastate kaupa) ja moodulite protokollide juures ei ole punasega.

**Comment by Lendaja** [comment]
Nüüd ka õpitulemustes sooritamise järjekorras, õppeaastate kaupa ning moodulite protokollides punasega.
Tehtud v 1.0.0

**Comment by AnuPiirisild** [comment]
tehtud
