### ISSUE TITLE
Õppuri andmete muutmise väli

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#199]
Õppuri andmete muutmisel peab olema näha ka õppuri nimi, kelle andmeid täidetakse.
![image](https://user-images.githubusercontent.com/36628933/38082175-8f7307e4-334e-11e8-9642-f4173a5c9486.png)

**Comment by Lendaja** [comment]
tehtud ver 0.6.8

**Comment by AnuPiirisild** [comment]
Tehtud
