### ISSUE TITLE
Uue õppeasutuse lisamine

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#2]
Andis veateadet "size code" - kuna ei näita, millise reaga viga on, siis ei tea mida muuta. Probleem oli siis lühinimes. Kui pikk lühinimi võib olla?

**Comment by irinakelder** [comment]
Parandatud (v 0.2.1). Vigaseid välju näidatakse punase joonega ja välja joone lõpus (all) kuvatakse sisestatud sümbolite arvu ja lubatud sümbolite arvu väljal.
