### ISSUE TITLE
Logib süsteemist välja salvestamisel

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#20]
Püsiandmed – õppeasutuse õppeastmete salvestamisel logitakse kasutaja automaatselt süsteemist välja, kui vajutada „salvesta“ nupule.

Mul läks tükk aega, enne kui õnnestus korrata - seega ei ole veel saanud täpselt aru, mis tingimustel seda teeb.

**Comment by irinakelder** [comment]
Palun täpsustada

**Comment by Helenvaltmann** [comment]
Login sisse kasutajaga Test2Kasutaja2. Avan Püsiandmed - sealt Õppeasutuse õppetasemed - linnutan õppetaseme (kood 408) scrollin lehekülje lõppu ja vajutan Salvesta. Paremal on sisselogitud kasutaja Test2Kasutaja2 asemel on Logi sisse. Pilt lisatud
![github4](https://user-images.githubusercontent.com/26483158/27080763-fa12835a-5045-11e7-9709-18ab5a8060bb.jpg)

**Comment by Lendaja** [comment]
Parandus tarnes 0.3.1

**Comment by Helenvaltmann** [comment]
korras, aitäh!
