### ISSUE TITLE
Tunniplaani kuvada tunnitüüp

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#201]
Tunniplaani koostamise hetkel on tundide juures kirjas, kas tegu e-õppe või seminariga vms. Seda infot palun kuvada ka lõplikus tunniplaani vaates. Tunniplaanis kuvada eriliiki tunde erineva värviga ja lisada legend. 
See peaks olema E-õpe, kuid tunniplaanis ei erista:
![image](https://user-images.githubusercontent.com/36628933/38083538-8b179896-3352-11e8-8150-7c6cc8dcf1b2.png)

**Comment by Lendaja** [comment]
tehtud ver 0.7.0

**Comment by AnuPiirisild** [comment]
Korras, testitud versioonis 0.7.0
