### ISSUE TITLE
Rühmaotsingu tulemustesse kuvada ka rühmajuhataja

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#202]
https://tahvel.edu.ee/#/studentgroups?_menu
Menüüribale ja tulemustesse lisada ka Rühmajuhataja:
![image](https://user-images.githubusercontent.com/36628933/38084117-4d9eec2e-3354-11e8-8e4e-11cb659c7b8b.png)

Versioon 0.6.6

**Comment by Lendaja** [comment]
tehtud ver 0.6.8

**Comment by AnuPiirisild** [comment]
Tehtud
