### ISSUE TITLE
Tunniplaani haldamise vaates perioodid ühtses järjestuses

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#204]
https://test.tahvel.eenet.ee/#/timetable/timetableManagement?_menu
Tunniplaani haldamise vaates kuvada kuupäevade järjestuses nii, et varasem on eespool. Lisaks lisada perioodi alusel sorteerimise võimalus (veeru pealkirjal klikkides), et saaks ka vastupidi valida.

**Comment by Lendaja** [comment]
tehtud ver 0.7.0

**Comment by Helenvaltmann** [comment]
toimib
