### ISSUE TITLE
Päevikus mooduli juurde rakenduskava nimetus

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#205]
Päeviku vaates kuvada mooduli juurde ka rakenduskava nimetus.
![image](https://user-images.githubusercontent.com/36628933/38085559-9f5608fe-3359-11e8-8fe2-36b986ea306a.png)

**Comment by Pirgit** [comment]
Hetkel kuvatakse sulgudes õppekava, selle asemel kuvada rakenduskava.

**Comment by Lendaja** [comment]
Tehtud ver 1.0.4

**Comment by AnuPiirisild** [comment]
Tehtud.
