### ISSUE TITLE
Õpperühmade vaikimisi vaade

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#206]
Õpperühmade vaikimisi vaates kuvada ainult aktiivsed õpperühmad. Ülejäänud tuleksid välja otsinguga.
https://tahvel.edu.ee/#/studentgroups?_menu

**Comment by Lendaja** [comment]
tehtud ver 0.7.0

**Comment by AnuPiirisild** [comment]
Toimib, versioon 0.7.0.
