### ISSUE TITLE
Kasutajatoe e-mail esielehele

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#207]
**tahvel@hitsa.ee** lisada esilehele enne versiooni infot:
![image](https://user-images.githubusercontent.com/36628933/38086132-e960f7b8-335b-11e8-8fa0-f5c8e6e353f4.png)

**Comment by Pirgit** [comment]
Lisaks tuleb versiooni alla lisada ESF logod.

**Comment by Lendaja** [comment]
tehtud ver 0.6.7
