### ISSUE TITLE
Ülekandmisel päeviku sissekande täpitähed sümbolitena

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#208]
Andmete ülekandmisel on päevikute sissekannetes tulnud täpitähed sümbolitena (Valga ja Järvamaa).
Näiteks:
VKOK
![image](https://user-images.githubusercontent.com/36628933/38187956-7bd9e150-3662-11e8-861c-72bc126177b5.png)
JKHK
![image](https://user-images.githubusercontent.com/36628933/38188016-ab382d62-3662-11e8-9f66-96a94a73b0db.png)

**Comment by Pirgit** [comment]
Kas seda on võimalik automaatselt parandada?

**Comment by Lendaja** [comment]
skript saadetud 13.04.18
