### ISSUE TITLE
Õppuri vaates puudub võimalus puudumistõendit lisada

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#209]
Olustverel töökeskkonnas õpilastel puudub võimalus lisada puudumistõendit.
Kahjuks ei ole meil võimalik seda kontrollida aga nende sõnul on nad õpilase vaates seda kontrollinud. 

Testkeskkonnas on võimalik minul õppurina puudumistõendit lisada. Kas võib olla andmete ülekandmisega seotud?

**Comment by Lendaja** [comment]
Kas on Olustveres täidetud tingimus: õppur on täisealine ning ei vaja esindajat (märkeruut muutmise vormil „Õppuril peab olema esindaja“ ei ole valitud)?

**Comment by Lendaja** [comment]
Ei ole viga.

**Comment by Pirgit** [comment]
Lisatööna pilet 240
