### ISSUE TITLE
Õppekava sisestamise valik vastavalt õpetatavale tasemele

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#21]
EBS kommentaar:
1)	Kõrgharidusõppe vaates võiks mitte olla nähtav „kutseõppe õk sisetsamine“.

Kas oleks võimalik kuvada õppekava sisestamine vastavalt valitud koolis õpetatavatele tasemetele?

**Comment by Pirgit** [comment]
Sama teema veel teises vaates: 
Kõrghariduse vormil ei tohiks olla näha „esindajate avaldused“ ja „esindajaks saamise avaldus“ ja muu kõrgharidusse mittepuutuv info.

**Comment by Pirgit** [comment]
EBS-st veel: Õpperühmade otsing – ei tohiks olla otsingus näha „rühmajuhataja“

Samas tuleks arvestada koolidega, kes annavad mõlemat tüüpi haridust. Arutame lahenduse võimalusi.

**Comment by irinakelder** [comment]
Peab nii tegema

**Comment by Lendaja** [comment]
Tehtud (v 0.3.0).

**Comment by Helenvaltmann** [comment]
õppekavasid kuvab vastavalt õppeasutuse õppetasemetele. See toimis ka kenasti ühise testimise ajal.
Samuti kuvatakse õpperühmade otsingus rühmajuhataja kutseõppes. 
Kui ma sellest avalduste asjast nüüd õigesti aru sain, siis on minu meelest ka korras, sest Tehnikakõrgkooli kasutaja 37501010000 ei saa koostada avaldust esindajaks saamise kohta.
