### ISSUE TITLE
Teiste õppurite andmete nägemine

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#210]
Kutseõppe vaates eemaldada õpilastelt teiste õpilaste (va enda rühma) nägemise õigus.
Versioon 0.6.6.

**Comment by Lendaja** [comment]
Vastuolu - on tehtud uus pilet 262 , et õpilane ei tohi teiste õpilaste andmeid üldse näha.

**Comment by AnuPiirisild** [comment]
Hetkel tehtud #262 väljapakutud versioon. II etapis juurde lahendus, kus koolipõhiselt saab valida, kas õppur näeb oma rühma õppijate nimekirja või mitte. _Tõstetud Jira'sse: TAHVEL-46_
