### ISSUE TITLE
Tunniplaani haldamine - õppekavad ja õpperühmad tähestikulises järjekorras

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#211]
Tunniplaani haldamises õpperühmade list  palun panna tähestikulisse järjekorda.
Õppetöö ettevalmistus -> Tunniplaani haldamine -> vali periood
Hetkel segamini:
![image](https://user-images.githubusercontent.com/36628933/38237757-b3092356-3730-11e8-834a-cf39e22112cc.png)

Versioon 0.6.6.

**Comment by Pirgit** [comment]
Järjestada esialgu õppekavade alusel ja siis õpperühma alusel tähestikulises järjekorras.

**Comment by Lendaja** [comment]
tehtud ver 0.6.7

**Comment by Lendaja** [comment]
tehtud ver 0.6.8

**Comment by AnuPiirisild** [comment]
Tehtud
