### ISSUE TITLE
"Muuda" nupp nähtavamale

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#214]
MUUDA/VAATA/TÄIDA nupud jäävad paremas servas sageli ekraanilt välja. Kasutajale ebamugav. Tuua nn aktiivsustsooni.

_Administratiivse töötaja vaade:_
Õppekavad -> Kooli õppekavad
![image](https://user-images.githubusercontent.com/36628933/38250299-1bdad0fc-3757-11e8-85a7-ac48f2290dd4.png)
Õppurid -> Õpperühmad
![image](https://user-images.githubusercontent.com/36628933/38250347-3a596926-3757-11e8-96af-369ef011187e.png)
Dokumendid -> Praktikalepingud
![image](https://user-images.githubusercontent.com/36628933/38250372-47906ef0-3757-11e8-93ab-f62d1eb3f623.png)
Õpetajad ->
Dokumendid -> VÕTA
Õppetöö -> Päevikud (kutse)
Õppetöö → Õppematerjalid (kutse)
Õppetöö -> Moodulite protokollid
Õppetöö ettevalmistus -> Kutseõp. tunnijaotusplaan
Seaded -> Kasutajad

_Õpetaja vaade:_
Õppetöö -> Päevikud (kutse)
Õppetöö → Õppematerjalid (kutse)
Õppetöö -> Moodulite protokollid
Praktika ja lõpetamine -> Praktikapäevikud

_Õppuri vaade:_
Minu õppeinfo -> Praktikapäevikud
![image](https://user-images.githubusercontent.com/36628933/38250423-6bb5109c-3757-11e8-9807-d5c52104e949.png)

Versioon 0.6.6.

**Comment by Pirgit** [comment]
Hetkel on lahendatud päeviku vaates mure - päevikut avades on kohe muutmise vaates. Tuleb läbi mõelda kogu süsteemi loogika mõttes, kuidas seda lahendada. Nupp on üldiselt pigem kõige ees või kõige taga - üldjuhul teise/kolmanda tulbana seda ei kuvata.
