### ISSUE TITLE
Uus sissekanne päevikus - nupu asukoha muutmine

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#216]
Päevikusse uue sissekande lisamise nupp võiks olla _H - hilinemine, ..._ peal. Kui päevikus õppurite nimekirjad pikad, siis hetkel peab kaua kerima, et uut sissekannet saaks lisada.
![image](https://user-images.githubusercontent.com/36628933/38253029-48026ecc-375e-11e8-8197-62e8608fc0bb.png)

Toome kõik nupud üles

**Comment by Lendaja** [comment]
tehtud ver 0.6.8

**Comment by AnuPiirisild** [comment]
Tehtud
