### ISSUE TITLE
Klikitavate ridade selgus

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#217]
Read ja sissekanded, millel saab klikkida ja avada, võiks olla äratuntavamad, nt kursoriga peale liikudes muutuvad aktiivseks. Millised oleksid võimalused?

**Comment by Lendaja** [comment]
tehtud ver 0.6.8  - link "Ava"

**Comment by AnuPiirisild** [comment]
Tehtud
