### ISSUE TITLE
Õppuri vaates akadeemiline puhkus, kuigi sellekohast infot ei ole admin vaates

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#218]
Järvamaa Kutsehariduskeskuses on õpilase vaates üldteadete all näha, et 
02.04.2018 | Akadeemilisele puhkusele viimine   Õpilane on viidud akadeemilisele   puhkusele.

Õpilasega ei ole seotud ühetgi käskkirja või avaldust, mis sellele viitaks.

**Comment by Lendaja** [comment]
Selle üldteate, mida kuvati õppuritele,  sisestas kool ise üldteatena.
