### ISSUE TITLE
Teema maht tundides: 4-kohaline arv

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#219]
Muuda mooduli andmeid -> Teema lisamine 
Tundide mahu piirab 3-kohalisena. Vaja on 4-kohalist võimalust
![image](https://user-images.githubusercontent.com/36628933/38419058-92bcaa04-39a7-11e8-81b8-9cdf998b449c.png)

_Versioon 0.6.7._

**Comment by Lendaja** [comment]
töös

**Comment by Lendaja** [comment]
tehtud v 1.0.0

**Comment by AnuPiirisild** [comment]
Tehtud, testitud versioonis 1.0.0.
