### ISSUE TITLE
Õppekava maht

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#22]
EBS: Sisestamine. Miks on „õppekava maht“ lahtris 25 tähemärki, kui sisestada saab vaid numbreid komakohtadega? 
Pirgit: 25 tähemärki on õppekava kood, õppekava maht on tegelikult veel pikem väli. Uurin arendajalt, miks selline valik.

**Comment by irinakelder** [comment]
Ei ole viga, 0/25 käib õppekava koodi kohta.

**Comment by Helenvaltmann** [comment]
Lubab sisestada 3 tähemärki ja siis teatab, et "Peab olema kuni 3-kohaline number!"  Mina sõnastaksin selle ümber, sest õppekava võib ju ka olla vähem kui 3 tähemärki. Kas; "Võimalik sisestada kuni 3-kohaline number" vms. Pirgit ütleb kuidas oleks õige ja kas üldse on vaja muuta:)
