### ISSUE TITLE
Päevikusse rohkem tunde valikusse

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#220]
Päevikus sissekande tegemisel hetkel valida kuni 5 tundi. Vajadus kuni 10 tundi.
![image](https://user-images.githubusercontent.com/36628933/38419964-f6bbd374-39aa-11e8-9fad-60c2e6473187.png)

Testitud _Versioon 0.6.7._

**Comment by Pirgit** [comment]
Lisatud on 12
