### ISSUE TITLE
Tunniplaani asendused

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#221]
Kust kohast sisestatakse tunniplaani õpetajate asendused.
Detailanalüüsi dokumendis Tunniplaan on kirjas p.5.6.1. Kasutuslugu: _1.Kasutaja navigeerib tunniplaani asenduse sisestamise vormile_ 
Ei leidnud seda kohta üles.

**Comment by Lendaja** [comment]
Uued arendustööd tabelis selle piletiga seotud: "Muuta tunniplaanis õpetajat või ruumi. Õppurite teavitamine muudatusest." on tehtud varem. Teade saadetakse ainult siis, kui tunniplaan on avalikustatud ja tunni juures (tunniplaani haldamine) tehakse muudatus.

Õpetajate asendamiseks tunniplaanis sellise teise õpetajaga, kes ei ole päevikuga seotud: 
- kutses uus õpetaja lisada tunnijaotusplaanis
- kõrges lisada uus õpetaja aine-õppejõu paarile (või koormuste planeerimise kaudu lisada õppeainele).

**Comment by Pirgit** [comment]
Asendusi saab teha sündmuste alt ning tunnjaotuskavas. 
Koormuses peab see ka kajastuma.

**Comment by AnuPiirisild** [comment]
Kuidas ikkagi teha õpetaja asendamist **sündmuse** alt? 
Saan sündmusena lisada uusi sündmuseid, kuid ei näe võimalust sündmuse alt õpetaja asendamist teha (näiteks otsida olemasolevat tundi, et sinna õpetaja vahetus teha?). Tunniplaani haldamise lehel saan valida varem tunnijaotusplaanis sisestatud õpetajate vahel, kuid tunniplaani haldamise lehel vahetusõpetajat sisestada ei saa. 
Mina näen praegu ainsa võimalusena protsessi: lisada tunnijaotusplaani alt õpetaja (läheb ka koormusesse), siis tunniplaani haldamise alt teha õpetaja vahetus.

**Comment by AnuPiirisild** [comment]
Sündmuste alt asendamised tehtud. Mugavama versiooni tarbeks avatud teema arendusetepanekutes.
