### ISSUE TITLE
Õpetajate vaates kuvada aktiivsed 

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#222]
"Õpetajad" alt vaikimisi kuvada aktiivsed õpetajaid. 
Praegu näitab läbi ajaloo kõiki õpetajaid. Mitteaktiivsed õpetajaid saab kätte otsingu abil.

**Comment by Lendaja** [comment]
töös

**Comment by Lendaja** [comment]
Tehtud ver 1.0.1

**Comment by Helenvaltmann** [comment]
toimib, aitäh, panen pileti kinni
