### ISSUE TITLE
Õpetaja puudumise info jõudmine Tahvlisse/tunniplaani

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#224]
Kui tunniplaan on juba tehtud ja hiljem selgub (näiteks RTIP'st), et õpetajat ei ole sel ajal - kuidas info tuleb Tahvlisse ja/või tunniplaani?

**Comment by Pirgit** [comment]
Peaks tulema admin töötajale automaatne teade, kui õpetaja on lisanud sündmuse (RTIP puudumine on sündmus), mis kattub tunniplaanis tema kirjega.

**Comment by Lendaja** [comment]
koosolekul 04.06 lepiti kokku: II etapp. Võimalik lahendus: konflikti olemasolu kuvamine admin töötaja avalehel – näidatakse hüüumärki, et on konflikt; sündmuste otsingu vormile lisatakse märkeruut „Otsi konflikte“

**Comment by AnuPiirisild** [comment]
_Tõstetud Jirasse: TAHVEL-44_
