### ISSUE TITLE
Tulp kitsamaks: Planeeritud ja sissekantud tundide arv

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#225]
Päevikud (kutse): tulba pealkiri _Planeeritud ja sissekantud tundide arv_ on liiga lai
https://test.tahvel.eenet.ee/#/journals?_menu 
![image](https://user-images.githubusercontent.com/36628933/38577381-665165da-3d09-11e8-9236-9f0c4b676294.png)
Sõnastus võiks olla _planeeritud/sissekantud_

**Comment by Pirgit** [comment]
"tundide arv" järgmisele reale

**Comment by Lendaja** [comment]
töös

**Comment by AnuPiirisild** [comment]
Tehtud, testitud versioonis 1.0.0.
