### ISSUE TITLE
Tunnijaotuskava vaade lühemaks

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#227]
Tunnijaotuskava vaade on liiga lai. 
Selgitus: ühe perioodi kokku-lahti tegemine.

**Comment by Lendaja** [comment]
Lühemaks ei tee. Teeme soovitud külmutatud päised + kerimisriba.

**Comment by AnuPiirisild** [comment]
Tehtud versioon 0.6.8.
