### ISSUE TITLE
Õppeaeg kuud võiks olla mittekohustuslik

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#23]
EBS: Sisestamine. Arusaadav, miks on aastate määratlus kohustuslik väli, aga kuud ei peaks olema kohustuslik, et lihtsalt tühja väärtust ehk „0“ märkida.
Ettepanek: aastad kohustuslik, kuud vabatahtlik väli. 
Pirgit: Nõus EBS ettepanekuga

**Comment by irinakelder** [comment]
Teeme mittekohustuslikuks, vaikimisi kuude arvu väljal on 0

**Comment by Lendaja** [comment]
Tehtud (v 0.3.0).
