### ISSUE TITLE
Õppekavadel vaikimisi ei kuvata suletud õppekavasid

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#230]
Hetkel õppekavade vaadet avades kuvatakse kõik õppekavad, mis koolis olemas on. Kui panna vanad õppekavad kinni (sulge õppekava), siis neid kuvatakse ikkagi, lihtsalt staatuseks on "suletud". Suletud õppekavad võiks olla vaikimisi mitte kuvatud, tuleksid välja otsinguga.

**Comment by Pirgit** [comment]
Vaikimisi ei kuvata suletud õppekavasid.

**Comment by Lendaja** [comment]
tehtud ver 0.7.0

**Comment by AnuPiirisild** [comment]
Töötab, testitud versioonis 0.7.0
