### ISSUE TITLE
Õppekavade nimekirja kuvada HTM kood

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#231]
Õppekava HTM kood kuvada ka õppekavade loetelu tulbas:
![image](https://user-images.githubusercontent.com/36628933/38602920-e2c33d26-3d74-11e8-8c89-1542e99cdc09.png)
https://test.tahvel.eenet.ee/#/curriculum?_menu

**Comment by Pirgit** [comment]
kõikides vaadetes kooli õppekava otsingu tulemustes kuvada ka HTM kood

**Comment by Lendaja** [comment]
töös

**Comment by Lendaja** [comment]
tehtud ver 1.0.1

**Comment by Helenvaltmann** [comment]
toimib, aitäh, panen pileti kinni
