### ISSUE TITLE
Rühmale teate saatmine

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#232]
Administratsiooni ja õpetaja vaatest ei saa rühmale teateid saata, eeldab ka õpilaste valimist. Annab veateate.
https://test.tahvel.eenet.ee/#/message/new?backUrl=received
![image](https://user-images.githubusercontent.com/36628933/38603626-c6f9673a-3d76-11e8-9069-13d493ef4649.png)

**Comment by Pirgit** [comment]
Ver 0.6.9
Kutseõppes ei saa rühmale teadet saata, kuna rühma nimekirja ei kuva. Ei kuvata admintöötajale ja ka rühma juhatajale - mõlemas vaates kontrollitud.
