### ISSUE TITLE
Õpilase päeviku otsingu vaatesse mooduli ja õpetaja nimi

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#235]
Õpilase vaates Minu õppeinfo ->Päevik: lisada vaatesse õpetaja nimi ja mooduli nimi.

**Comment by Lendaja** [comment]
Tehtud ver 1.0.1

**Comment by Helenvaltmann** [comment]
olemas, aitäh, panen pileti kinni
