### ISSUE TITLE
Õpilase päeviku sissevaatesse õpetaja, moodul, puudumised

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#236]
Õpilase vaade, päeviku detailsem vaade:
![image](https://user-images.githubusercontent.com/36628933/38605328-ab4ce80e-3d7b-11e8-9924-6f6cb60a5241.png)

Lisada mooduli nimi, õpetaja nimi, puudumised (õpilane nägema, mis kuupäevadel ta on päevikus puudujaks sisestatud).

**Comment by Helenvaltmann** [comment]
olemas
