### ISSUE TITLE
EKAPite ümardamised

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#238]
JKHK: Moodulite rakenduskavasse teemade lisamisel arvutab süsteem sisestatud tundide arvu järgi EKAP-ite arvu ja ümardab 1 koht peale koma. Tundub, et sama ümardatud arvu kasutatakse hiljem antud mooduli õppeaasta EKAP-ite arvu leidmisel. Kui on mitu ümardatud arvu, siis võib juhtuda, et ehkki erinevate päevikute mahud annavad kokku täpselt täisarvu EKAP-eid, näitab rakenduskava 0,1 EKAP-it väiksemat või suuremat mahtu. (Mooduli mahu arvutamisel võiks võtta arvesse täpse arvu, mitte ümarduse.)

TTHK: Tundide jaotus komakohtadega ei klapi ja hakkab veateateid andma.

**Comment by AnuPiirisild** [comment]
Näiteks kuvab ka õpilase õpitulemustes sellist komakohtadega vaadet (JKHK, Belov):
![image](https://user-images.githubusercontent.com/36628933/38612712-3b2d1142-3d90-11e8-9b1d-b335c73c119e.png)
![image](https://user-images.githubusercontent.com/36628933/38612759-5ad8ea5c-3d90-11e8-9901-318071600ada.png)

_Versioon 0.6.7._

**Comment by Lendaja** [comment]
EKAP ümardamine tehtud ver 0.6.8

**Comment by AnuPiirisild** [comment]
Tehtud
