### ISSUE TITLE
MUUDA nupp päeviku juures 

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#239]
Kui isikul on õigus päevikut muuta, siis talle avaneb kohe muudetav vaade, mitte ei pea lisaklikki tegema.

Kinnitatud päevikutes on muuda nupp päeviku avamisel vastavalt sellele, kas on õigus muuta.

**Comment by Lendaja** [comment]
Mida siin mõeldud on? Teeme: päeviku (kutse) otsinguvormilt avanevas tabelis, kui klikkida päeviku nime lingil, avaneb päevikus "päeviku täitjaks"  märgitud kasutajale päeviku muutmisvorm.

**Comment by Lendaja** [comment]
tehtud ver 0.6.8

**Comment by AnuPiirisild** [comment]
Tehtud
