### ISSUE TITLE
Veateate sõnastus

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#24]
Veateade "Peaeriala maht peab olema mitte suurem, kui õppekava maht (60 EAP)"

**Comment by irinakelder** [comment]
Peab olema "Peaeriala maht ei tohi olla suurem kui õppekava maht (60 EAP)"

**Comment by Lendaja** [comment]
Tehtud (v 0.3.0).

**Comment by Helenvaltmann** [comment]
olemas, panen pileti kinni
