### ISSUE TITLE
Päevikus sissekannete tulbad kitsamaks

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#241]
Päeviku sissekannete tulbad on liiga laiad, piisab kitsamast, sest kui on palju sissekandeid, siis läheb ekraanilt välja.
![image](https://user-images.githubusercontent.com/36628933/38608762-eebe5038-3d84-11e8-9690-f45a5a372efe.png)

**Comment by Lendaja** [comment]
tehtud ver 0.6.8

**Comment by AnuPiirisild** [comment]
Tehtud
