### ISSUE TITLE
Päeviku sissekandel kuvada päeviku nimi

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#242]
Päevikusse uut sissekannet tehes, et oleks silme ees päeviku nimi.
![image](https://user-images.githubusercontent.com/36628933/38609064-cebcb40e-3d85-11e8-94e9-145d534de90c.png)

**Comment by Lendaja** [comment]
tehtud ver 0.6.8

**Comment by AnuPiirisild** [comment]
Tehtud
