### ISSUE TITLE
Õppematerjali selgitav info nähtavale

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#243]
Õpilase vaates õppematerjali juurde sisestatud selgitavat infot pole hetkel näha:
![image](https://user-images.githubusercontent.com/36628933/38609305-61767a8c-3d86-11e8-930a-370827aa3c91.png)

Selgitav info seal oli:
![image](https://user-images.githubusercontent.com/36628933/38609333-70370d02-3d86-11e8-9d6f-c676bcecd917.png)

**Comment by Pirgit** [comment]
lisada nimetuse ja lingi vahele tulp selgitav info.

**Comment by AnuPiirisild** [comment]
"Kirjeldus" asemel "Kirjeldus õpetaja jaoks"

**Comment by Lendaja** [comment]
tehtud ver 0.6.8

**Comment by AnuPiirisild** [comment]
Tehtud
