### ISSUE TITLE
Akad. puhkuse taotluses perioodi täpsustus

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#245]
Akadeemilise puhkuse taotlust täites perioodi valides kuvab kõiksugu perioodid valikusse. 
Vaja täpsustuseks näiteks õppeaastat juurde.

![image](https://user-images.githubusercontent.com/36628933/38612252-c84dabc4-3d8e-11e8-8556-39d26e314813.png)

**Comment by AnuPiirisild** [comment]
Sama mure õppetoetuste vormistamise lehel
Seaded -> Õppetoetused -> Lisa uus
Õppeperioodi valiku väli:
![image](https://user-images.githubusercontent.com/36628933/39288480-d42c648c-4930-11e8-9733-a1b53bf02baa.png)

**Comment by Lendaja** [comment]
Akad. puhkuse osas tehtud ver 0.6.9

**Comment by AnuPiirisild** [comment]
Töötab, testitud versioonis 0.7.0
