### ISSUE TITLE
Õpetaja kontakttelefon mittekohustuslikuks väljaks

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#248]
Õpetaja andmete lisamise vaates ka _Kontakttelefon*_ väli teha mittekohustuslikuks.

![image](https://user-images.githubusercontent.com/36628933/38794801-f4921a52-415e-11e8-8aef-e25aed9b14a1.png)

_Testitud versioonis 0.6.7._

**Comment by Helenvaltmann** [comment]
toimib, aitäh, panen kinni
