### ISSUE TITLE
Teateribal klikates teateväli kohe avanema

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#249]
Esilehel kuvatavad teadete väljad: kogu hallil välja piirkonnal klikates võiks avaneda, mitte ainult noole peal vajutades, sest nool on liiga kaugel paremas servas.
![image](https://user-images.githubusercontent.com/36628933/38796499-48387084-4164-11e8-8af0-366ef1484326.png)

**Comment by Lendaja** [comment]
Disain muudetud, ei ole halli riba ver 0.6.9

**Comment by AnuPiirisild** [comment]
Endiselt tuleb otsida avamise ikooni. Tõstetud UX ettepanekutesse.
