### ISSUE TITLE
Õppekava muutmine

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#25]
Muuda nupp võiks olla ka adminil kohe õppekava all, mitte ainult siis, kui ma õppekava otsingust valin "muuda".

**Comment by irinakelder** [comment]
Lisame muuda nuppu readonly vormile admin töötaja vaates

**Comment by Lendaja** [comment]
Tehtud (v 0.3.0).

**Comment by Helenvaltmann** [comment]
olemas, pilet kinni.
