### ISSUE TITLE
Avalduse kinnitamine ilma lapsevanema loata

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#250]
Kui õppurile on määratud esindaja, siis süsteemis on võimalik temast mööda minna taotluse koostamise hetkel, kui õppur vajutab Salvesta, kuid pole vajutanud veel Esita nuppu – admin töötajale juba tekib taotlus üles ning juures märge, et lapsevanem on JAH öelnud. Samuti saab ilma lapsevanema kinnituseta tõendi soovi käskkirjale lisada.

Täpsemalt:
Õppur, kel määratud esindaja, täidab taotluse. Kohe pärast SALVESTA vajutamist, tekib märge lapsevanema kinnituse kohta, kuigi lapsevanem pole veel kinnitatud:
![image](https://user-images.githubusercontent.com/36628933/38924790-87bf76f0-4306-11e8-95a8-447d92edbfb1.png)

Alles pärast ESITA nupu vajutamist tekib märge, et lapsevanem pole kinnitanud:
![image](https://user-images.githubusercontent.com/36628933/38924853-b1f9a10c-4306-11e8-99ea-9320d30283cc.png)

Admin töötaja vaates, kui õppur on avalduse sisestanud ja salvestanud, kuid pole veel esitanud, on admin töötaja vaates juba info:
![image](https://user-images.githubusercontent.com/36628933/38924915-dd663544-4306-11e8-8aa7-21d54cd4b86c.png)

Kui admin töötaja vajutab kohe ESITA, kuvab:
![image](https://user-images.githubusercontent.com/36628933/38924954-f005458c-4306-11e8-8441-2911ad15b8ac.png)

Lapsevanema vaates näitab seejärel nii:
![image](https://user-images.githubusercontent.com/36628933/38925239-b91847e4-4307-11e8-9ea2-2c105d7cb4bf.png)

Kui õppur vajutab Esita, siis tuleb lapsevanemale nähtavale nii nagu peab:
![image](https://user-images.githubusercontent.com/36628933/38925293-dcbe6476-4307-11e8-8e3a-3055bcadedc8.png)

**Comment by Lendaja** [comment]
Arenduskeskkonnas ei teki seda viga. Palun andmeid, mis koolis, millise õppuriga testimisel viga tekkis.

**Comment by Lendaja** [comment]
tehtud ver 0.6.9

**Comment by AnuPiirisild** [comment]
Õpilase vaates peale avalduse salvestamist tuleb lapsevanema kinnituse kohta **EI** ning õpilane ise esitada ei saa, saab vaid salvestada - kõik õige. Admin.töötaja vaates avalduste all ta näeb seda salvestatud avaldust, avades on lapsevanema kinnituse kohta märgitud **EI**. Kuid kui admin.töötaja siiski vajutab Esita, muutub lapsevanema kinnitus, ilmub **JAH**.

**Comment by Lendaja** [comment]
ver 0.7.0

**Comment by AnuPiirisild** [comment]
Tehtud, versioon 0.7.0
