### ISSUE TITLE
Õppur andmete muutmine

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#251]
Õppur peab saama oma kontonumbrit lisada ja muuta.
Administratiivne töötaja peab saama muuta õppuri: Suhtluskeel, Arveldusarve, Õpipoisi ettevõte, Õpilaskodu koht, Eelnevalt lõpetatud õppeasutus, eelnevalt hariduse lõpetamise aasta, kodakondsus.

**Comment by Pirgit** [comment]
"Lõpetamise aasta" - on varasemalt lõpetatud kooli lõpetamise aasta, muuta "Eelneva hariduse lõpetamise aasta"

**Comment by Lendaja** [comment]
töös,  "Lõpetamise aasta" asemel "Eelneva õppeasutuse lõpetamise aasta".

**Comment by Helenvaltmann** [comment]
Kõik toimib, panen pileti kinni, aitäh
