### ISSUE TITLE
Vanad struktuuriüksused õppetöögraafikus

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#252]
Õppetöö ettevalmistus -> Õppetöögraafik
Õppetöögraafikus kuvab ka kehtetuid struktuuriüksuseid. Kui struktuuriüksuse valikrealt kehtetud välja võtta, siis lehe uuesti laadimisel ilmuvad nad tagasi.

Näiteks testis Hitsa-kool, kus 2 struktuuriüksust on kuupäevaliselt kehtetud:
![image](https://user-images.githubusercontent.com/36628933/39186163-3dea3a3a-47d2-11e8-8866-96918bc896ba.png)

Kehtetuid struktuuriüksuseid õppetöögraafiku lehel kuvama ei peaks.

**Comment by Pirgit** [comment]
192 piletis on öeldud, et on realiseeritud, kuid live süsteemis 0.6.9 ei ole korras. 
Kuvab kõiki struktuuriüksusi ja neid valikust ära võttes, mis ei ole õppetööga seotud kuvab süsteemi viga. 
Testitud JKHK peal.

**Comment by Lendaja** [comment]
piletis 192 oli jutt rühmadest ja strukt üksused oli kirjas kooli soovina.
Struktuuriüksuse valik õppetöögraafiku vormil on sisuliselt otsingu parameetrid mida praegu süsteemis ei salvestata. 
Teeme: struktuuriüksuse valikus näidatakse valitutena ainult kehtivaid struktuuriüksuseid ja vastavalt näidatakse ka õppetöögraafikus kehtivaid struktuuriüksuseid. 
Kehtetud struktuuriüksused kuvatakse valikus loetelu lõpus ja ei ole vaikimisi valitud.

**Comment by Lendaja** [comment]
ver 0.7.0
