### ISSUE TITLE
Sõnastuse muudatus tunniplaanis

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#253]
Teise õpetaja tunniplaani vaadates näitab üksiksündmuste kohta "Kinni". Sõnastada kinni asemel "Hõivatud"
![image](https://user-images.githubusercontent.com/36628933/39238511-12a8f7b6-4887-11e8-9a13-428b49240b26.png)

**Comment by Helenvaltmann** [comment]
tehtud, aitäh
