### ISSUE TITLE
Sündmuses ajalises järjestuses

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#254]
Õpetaja vaade: Tunniplaan ja sündmused -> Sündmused
Admin.töötaja vaade: Õppetöö ettevalmistus -> Sündmused
Sündmuste vaate avamisel näitab uuemaid sündmuseid lõpus. Peab olema vastupidi.

**Comment by Helenvaltmann** [comment]
toimib, aitäh
