### ISSUE TITLE
Kutsestandardi kuvamine

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#255]
Kutsestandardi kuvamisel on vajalik lisada sulgudesse kehtivuse aeg. Hetkel ei ole aru saada, millise kutsestandardiga ma seon. 
Peaadminnina kompetentsiga sidumisel:
![image](https://user-images.githubusercontent.com/17288515/39359888-870e23da-4a24-11e8-9fd7-8e76285bf9e8.png)
![image](https://user-images.githubusercontent.com/17288515/39359948-d350c720-4a24-11e8-8116-64674457907a.png)

**Comment by Pirgit** [comment]
Lisaks kuvada kutsestandardi kehtib kuni sulgudes õppekava juures kutsestandardi valimisel.

**Comment by irinakelder** [comment]
töös

**Comment by Lendaja** [comment]
tehtud v 1.0.0

**Comment by AnuPiirisild** [comment]
Tehtud, _testitud versioonis 1.0.0._
