### ISSUE TITLE
Mooduli protokoll - kuvada ainult kehtivad RAKid

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#256]
Mooduli protokolli lisamisel tuleb valida rakenduskava. Rakenduskavade hulgas on rippmenüüs ka nende õppekavade rakenduskavad, mille staatuseks on „suletud“. Peab kuvama ainult neid rakenduskavasid, mille õppekava ei ole suletud.

**Comment by Lendaja** [comment]
Õppekava sulgemisel suletakse kõik seotud rakenduskavad.
Sellepärast ei tehta eraldi kontrolli, kas rakenduskava on seotud suletud õppekavaga. 
ver 0.7.0

**Comment by AnuPiirisild** [comment]
Tehtud, testitud versioonis 0.7.0
