### ISSUE TITLE
Tunnijaotuskava kustutamine

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#257]
Tunnijaotuskava ei ole võimalik kustutada. Vajalik on võimaldada kustutamine, kui tunnijaotuskava ei ole seotud ühegi päevikuga.

**Comment by Lendaja** [comment]
ver 0.7.0

**Comment by AnuPiirisild** [comment]
Tehtud, testitud versioonis 0.7.0
