### ISSUE TITLE
Rakenduskavast mooduli kustutamine

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#258]
Sisestamisel rakenduskavast peab saama moodulit kustutada.

**Comment by Pirgit** [comment]
Irina kommentaar - moodulit ei saa ega tohi saada kustutada kui see on juba seotud selliste asjadega nagu tunnijaotusplaan või õppuri tulemused

**Comment by Lendaja** [comment]
ver 0.7.0

**Comment by Pirgit** [comment]
Moodulit saab kustutada, kui andmeid on sisestatud. Kui on tehtud uus rakenduskava ja mooduli andmed ei ole sisestatud (ei ole korras), siis ei saa kustutada moodulit.
