### ISSUE TITLE
Koormusvaates õpetaja juures valed moodulid

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#259]
TTHK kuvab õpetaja juures mooduleid, millega ta ei ole seotud ja mida selles koolis ei antagi. TTHK ei kandnud andmeid üle vaid sisestas ise.
Päringud -> Õpetaja koormus
![image](https://user-images.githubusercontent.com/36628933/40786069-ddd44616-64f2-11e8-9407-f455e831df0a.png)

Sama asi testis HITSA koolis, nt:
![image](https://user-images.githubusercontent.com/36628933/40786392-9c0939fc-64f3-11e8-8570-8acd81ceecc1.png)

**Comment by Lendaja** [comment]
ver 0.7.0

**Comment by AnuPiirisild** [comment]
Tehtud, testitud versioonis 0.7.0
