### ISSUE TITLE
Väljade muutmine

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#26]
Näiteks õppekavas saan ma erinevaid välju muuta aga ei saa salvestada, kuna ma ei ole muutmiseks võtnud õppekava lahti. Ei tohiks saada siis ka muuta välju. 
Läbivalt süsteemis ei tohiks saada muuta välju, kui ei ole selleks õigust.

**Comment by irinakelder** [comment]
Read-only vaade ei tööta korrektselt

**Comment by Lendaja** [comment]
Tehtud (v 0.3.0).

**Comment by Helenvaltmann** [comment]
Õppekava ei saa enam muuta kui on vaatamiseks avatud.
