### ISSUE TITLE
Riiklikud õppekavad avalikud vaates nähtavaks

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#260]
Lisada riiklikud õppekavad (kinnitatud) avalikud vaates nähtavaks. Hetkel on nähtavad ainult koolide kinnitatud õppekavad.

**Comment by Lendaja** [comment]
tehtud ver 1.0.1

**Comment by Helenvaltmann** [comment]
olemas, aitäh, panen pileti kinni
