### ISSUE TITLE
Õpilaste andmed ei tohi olla nähtavad teistele õpilastele

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#262]
II etapis realiseeritakse kooli põhine valik. Seni ei tohi olla õpilaste andmed nähtavad teistele õpilastele ehk võtame terve menüüpunkti õpilase vaatest ära.

**Comment by irinakelder** [comment]
töös

**Comment by Lendaja** [comment]
tehtud v 1.0.0

**Comment by AnuPiirisild** [comment]
Tehtud, testitud versi0onis 1.0.0
