### ISSUE TITLE
Vabandatud puudumise korral sissekande lisamine 

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#263]
Koolid soovivad ka vabandatava puudumise korral lisada õpilase kohta sissekannet. Näiteks kui on oluline kontrolltöö, mida peab järgi tegema, siis lisatakse hinne samasse sissekandesse lihtsalt hiljem ja esialgu õpilasele X, et ta teaks, et peab midagi järgi tegema.

**Comment by irinakelder** [comment]
Hetkel see on täiesti toimiv võimalus.

**Comment by AnuPiirisild** [comment]
Töötab, testitud versioonis 0.7.0.
