### ISSUE TITLE
Õppetöögraafik nähtavaks

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#265]
Õppetöögraafik peab olema nähtav kõigile sisseloginud kasutajatele. 
Õpilase ja lapsevanema vaates vaikimisi tema rühma oma ainult valitud. Õpetaja vaates kõik õpperühmad.

**Comment by irinakelder** [comment]
töös

**Comment by Lendaja** [comment]
tehtud 1.0.1

**Comment by Helenvaltmann** [comment]
toimib kenasti. Vaikimis on minu õppetöögraafik aga kui linnuke ära võtta, kuvab nii õpilasel kui ka lapsevanemal kõik õppetöögraafikud
