### ISSUE TITLE
Uue kasutajana sisse logides süsteemi viga

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#267]
Kui kasutaja, kellel ei ole Tahvlis õigusi sisse logib, siis kuvab kasutajale korraks süsteemi viga.

**Comment by Lendaja** [comment]
Mismoodi kasutaja proovis sisselogida ja mida logi selle kohta näitab?
Kui ADga proovin test.tahvlis sisse logida, saan peale pikka ootamist punase teate "Sisselogimine ebaõnnestus".

**Comment by Lendaja** [comment]
töös

**Comment by Pirgit** [comment]
Kasutaja proovis sisse logida M-ID-ga

**Comment by Lendaja** [comment]
tehtud v 1.0.0
