### ISSUE TITLE
Rühmateate saatmine: nimekirjast eemaldamise ristikest pole

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#268]
Testis HITSA kool -> teadete saatmine õpperühmale
Valides rühma, kuvab õppurid, kuid nimekirjast eemaldamise ristikest ei näita.
![image](https://user-images.githubusercontent.com/36628933/41115955-ad482446-6a91-11e8-9edc-edfa916af8f0.png)

Kui sisestada nimesid ühe kaupa, on ristid olemas. Kui lisada rühm ning enne või pärast seda üksikult isik juurde, siis viimastele ristikest ei teki.

Testitud testis versioonis 0.7.0

**Comment by Lendaja** [comment]
Analüüsis p 3.2:
...	Ikoon „Kustuta“ – ikoonile vajutades kustutatakse lisatud isik teate küljest. Kustutamise ikoon kuvatakse ainult andmevälja ”Saaja nimi” otsingutulemustest valitud isikute korral.

**Comment by AnuPiirisild** [comment]
Tõstetud arendusettepanekutesse.
