### ISSUE TITLE
Moodulite järjekord rakenduskava trükifailis on segamini

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#271]
Rakenduskavas on moodulite trükifailis moodulite järjekord tähestiku järjekorras, kuid pole grupeeritud mooduli liigiti, st segamini on põhiõpingud, valikainete moodul, lõpueksam ja üldaineid.  (Vt näiteks _live_'s JKHK rakenduskava _Viimistlus 2018_. https://tahvel.edu.ee/#/vocationalCurriculum/194/moduleImplementationPlan/505/edit?_menu)
Koolid soovivad, et ka rakenduskava väljaprindi puhul oleks mooduli liikide kaupa ja seal sees omakorda tähestiku jrk.
(Kooli õppekava printfailis on grupeering kenasti olemas  (Vt näiteks _live_'s JKHK kooli õppekava _Ehitusviimistlus_.))
_Testitud versioonis 0.7.0._

**Comment by irinakelder** [comment]
töös

**Comment by Lendaja** [comment]
tehtud ver 1.0.1

**Comment by AnuPiirisild** [comment]
Testitud, töötab.
