### ISSUE TITLE
Rakenduskavas moodulite trükkimisel kuvab hindamiskriteeriumite all hindamisülesandeid

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#273]
Rakenduskavas moodulite trükkimisel kuvab praegu  hindamiskriteeriumite all hoopiski hindamisülesandeid.

Näiteks HITSA kool test-Tahvlis: _Õppekavad_ ->_Kooli õppekavad_-> _Hobuhooldaja Ühis-ÕK_ -> rakenduskava _HOBU ÜHIS-Hobuhooldaja Ühis-ÕK_ -> _Trüki moodulid_

Moodul _07. Hobumajandushoonete, rajatiste ja hobuinventari hooldamine_
Mooduli andmetes on kirjas:
![image](https://user-images.githubusercontent.com/36628933/41959437-a41b328c-79f5-11e8-8390-561f8f268e82.png)

Trükifailis kuvab:
![image](https://user-images.githubusercontent.com/36628933/41959569-026b6604-79f6-11e8-8501-13e64b1c76db.png)

_Testitud versioonis 1.0.0_

**Comment by irinakelder** [comment]
töös

**Comment by Lendaja** [comment]
tehtud ver 1.0.1

**Comment by AnuPiirisild** [comment]
Töötab.
