### ISSUE TITLE
Veateade tõendite tellimisel

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#275]
Õppur Anu HITSA koolis valib: Minu andmed -> DOKUMENDID -> TELLI TÕEND:
Kui õppur vajutab järgmiseks kinnitavalt _Telli tõend_, tuleb talle esmalt veateade
![image](https://user-images.githubusercontent.com/36628933/43309049-4e997ffe-918c-11e8-9941-175fcdab79b3.png)

Aga tegelikult admin töötaja vaatesse tõend ilmub ja saab Tõendi avada küll (MUUDA nupp) ja sellega edasi tegutseda.

Test-Tahvel, versioon 1.0.0

**Comment by Lendaja** [comment]
Teade on õige. Admin töötaja peab tellitud tõendit nägema. Tõend on staatuses "Tellimisel" ja kui vaadata EKISe andmevahetuse logi, siis on näha, et tõepoolest tõendi tellimine ebaõnnestus. 
Admin saab korraldada EKISes vajalikud seadistused.   Muuda nupuga avanevalt vormilt saab admin töötaja saata uuesti tõendi tellimuse.

**Comment by AnuPiirisild** [comment]
Aitäh

**Comment by AnuPiirisild** [comment]
Palume selle õppuri vaates tekkinud punasel teate sõnastus muuta järgnevaks:
**Tõendi tellimine edastatud. Tõend saabub Teile e-mailile, kui kool on selle digiallkirjastanud.**

**Comment by AnuPiirisild** [comment]
Sain teada, milles oli asi. Aitäh :)
