### ISSUE TITLE
Päeviku otsingusüsteemis ei näita vana õppeaasta omi

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#276]
Test-Tahvel, HITSA kooli, admin vaade: Õppetöö -> Päevikud (kutse): Otsinguparameetrid
Valin otsingusüsteemist eelmise õppeperioodi õppeaasta (2017/2018) ning soovin lisaks otsida päevikut, kuid valikusse annab vaid käimasoleva õppeperioodi päevikuid.
![image](https://user-images.githubusercontent.com/36628933/43571612-18a9f180-9646-11e8-9ced-672b01ab5f8d.png)

_Testitud versioonis 1.0.0_

**Comment by Lendaja** [comment]
Otsinguparameeter Päevik on nüüd autocomplete_ väli.
Tehtud ver 1.0.1

**Comment by AnuPiirisild** [comment]
Testitud, töötab.
