### ISSUE TITLE
Tunniplaani kellaajad on Google kalendrisse tõmmates on nihkes

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#277]
Testbaasis HITSA koolis tunniplaani alla laadides ning siis failiga oma Google kalendrisse importides näitab tundide algusaegu võrreldes Tahvli tunniplaaniga 7h nihkes. Proovisid Anu ja Pirgit kumbki oma kalendris. 
Tahvel:
![image](https://user-images.githubusercontent.com/36628933/44359385-66318e80-a4c0-11e8-8e88-f332e110ece5.png)

Google Drive
![image](https://user-images.githubusercontent.com/36628933/44359392-6d589c80-a4c0-11e8-8949-464f4fe9af1b.png)

Samas näiteks Outlooki kalendrisse tõmmates näitas kellaaegu õigesti.
Testitud versioonis 1.0.1

**Comment by Lendaja** [comment]
Tehtud ver 1.0.4

**Comment by AnuPiirisild** [comment]
Tehtud
