### ISSUE TITLE
Päeviku loomise juures seotud rühm loob salvesta nupuga korduseid

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#278]
Päevikut luues, kui siduda sellega rühm ning juhul kui rühma moodul ja teema on samad mis põhirühmal, siis nii mitu korda kui _Salvesta_ nuppu vajutan, nii mitu korda tuleb tunnijaotusplaani vaatesse seda teemat inforibale. (näiteks kui käin lisamas õpetajat või ruumi või niisama salvestan)

Päevikule lisatud rühm ja moodul, teema:
![image](https://user-images.githubusercontent.com/36628933/44483344-804fa600-a653-11e8-94c9-092568c9ebe5.png)

Mitmeid kordi on vajutatud _Salvesta_ nuppu:
![image](https://user-images.githubusercontent.com/36628933/44483459-d9b7d500-a653-11e8-85e3-309ed348fb06.png)

Testitud HITSA koolis, näiteks kui võtta Kutseõp. tunnijaotusplaan -> Ryhm 1 -> moodul 03. Toitlustamise alused -> Teema 3
Testitud versioonis 1.0.1

Kas olen tekitanud mingid muidu ebatõenäolised seosed?

**Comment by Lendaja** [comment]
tehtud ver 1.0.2

**Comment by AnuPiirisild** [comment]
Tehtud
