### ISSUE TITLE
Sündmuse sisestamisel päevikusse eksimusega kellaaja puhul vale kuva

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#279]
Õpetaja ja admin töötaja roll, Sündmuse sisestamine:

Sündmust sisestades on võimalik praegu panna kellaaeg valesti (lõpp on algusajast varasem):
![image](https://user-images.githubusercontent.com/36628933/44772063-88d53e80-ab75-11e8-933b-30e56eba2f23.png)

Tunniplaanis kuvab sel juhul nii:
![image](https://user-images.githubusercontent.com/36628933/44772118-b0c4a200-ab75-11e8-9502-d02f520f5e52.png)

Kui märgin nt ajad 11:00-08:00, siis kuvab tunniplaanis nii:
![image](https://user-images.githubusercontent.com/36628933/44772198-e10c4080-ab75-11e8-9230-ab66d063da99.png)

_Testidud versioonides 1.0.1 ja 1.0.2, test-Tahvlis, HITSA kool, (õpetaja, admin.töötaja Anu)._

**Comment by Lendaja** [comment]
tehtud v 1.0.3

**Comment by AnuPiirisild** [comment]
tehtud
