### ISSUE TITLE
TTHK 1. kursus ei näe eri- ja sõidutoetusi

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#283]
TTHK 1. kursuse õppurid (näiteks SKApe18) ei näe eritoetuse ja sõidutoetuse taotlemise võimalust.
Õppetoetuse koostamise ankeedil on märgitud, et ka 1. kursus saab taotleda. Õppevormid on õiged.

**Comment by Lendaja** [comment]
tehtud v 1.0.3

**Comment by AnuPiirisild** [comment]
_Tehtud, versioon 1.0.3_
