### ISSUE TITLE
Päeviku sissekandel tundide arv suuremaks

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#284]
TTHK ütles, et neil on 17 tundi päevas, mistõttu on vaja päeviku sissekande alla võimaldada nii algustund kui ka tundide arv 12 asemel 17.

![image](https://user-images.githubusercontent.com/36628933/45207865-d9dde480-b291-11e8-8fc9-3d0a2d33646b.png)

Kas on seda arendust võimalik kohe töösse võtta, sest kool juba käib ja sissekandeid tehakse.

**Comment by Lendaja** [comment]
Tehtud v 1.0.3

**Comment by AnuPiirisild** [comment]
_Tehtud, versioon 1.0.3_
