### ISSUE TITLE
Õpetajad peavad nägema ainult oma rühma õppurite puudumistõendeid

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#285]
Õpetajad, kes on märgitud rühma juhiks, peaksid nägema ainult oma rühma õppurite esitatud puudumistõendeid.
TTHKst üks õpetaja kirjutas: _Tänu mul on 279 tõendit._

**Comment by Lendaja** [comment]
Palun nagu tavaliselt täpsustada, milline õpetaja. Võib saata meilile.

**Comment by Lendaja** [comment]
Viga ei ole. Sellel õpetajal on nii õpetaja kui ka Admin töötaja roll ja admin töötajana ta näebki kõiki puudumistõendeid. Õpetajana näeb 20.

**Comment by AnuPiirisild** [comment]
Aitäh
