### ISSUE TITLE
päevikus kuvab lühendi PR asemel R

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#287]
Päevikus avades kuvab väljal "Õppetöö liikide planeeritud ja sissekantud tundide arv) PR lühendi asemel R.
![image](https://user-images.githubusercontent.com/36628933/46086332-871c8c00-c1b0-11e8-9e63-c4b826ddc046.png)

_Testitud versioonis 1.0.3_

**Comment by AnuPiirisild** [comment]
Näidet saab vaadata testkeskkonnas, HITSA koolis päevikus "inventariseerimine"
![image](https://user-images.githubusercontent.com/36628933/46127265-d7d7c780-c238-11e8-83c4-d992eb4112dc.png)

**Comment by Lendaja** [comment]
tehtud ver 1.0.4

**Comment by AnuPiirisild** [comment]
Tehtud
