### ISSUE TITLE
Päevikus sama päeva sissekandeid kuvab tagurpidi järjekorras

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#288]
LIVE keskkonnas (VIKK), kui samal päeval sisestada tunde, siis hilisemate tundide sissekanded on eespool ja varasemad tagapool. **Aga test-keskkonnas jäävad õiget pidi.**
Proovisin LIVE keskkonnas VIKK koolis Rakendusmatemaatika päevikuga (Õpetaja Orason). Sisestasin sama kuupäevaga esmalt hommikuse tunni ning seejärel õhtupoolse tunni. Päevikus näitas õhtupoolset eespool (jutt sellest tabelist, kuhu hindeid pannakse). Oma näited kustutasin sealt ära, kuid samas päevikus on näha 24.sept. kuupäevaga analoogne situatsioon:
![image](https://user-images.githubusercontent.com/36628933/46127009-e70a4580-c237-11e8-857e-a3d6ac2cb555.png)
Kooli väitel tekitab see segadust.

Testitud versioonis 1.0.3

**Comment by Lendaja** [comment]
Tehtud ver 1.0.4

**Comment by AnuPiirisild** [comment]
Tehtud
