### ISSUE TITLE
VIKK ei saa õpetajana grupile enam teadet saata

### ISSUE THREAD

**Issue by AnuPiirisild** [hariduspilv/oppeinfo#289]
Katriin Orason (VIKK) ei saa õpetaja rollis olles õppegrupile teadet saata: pärast "Sihtgrupp" valimist kui läheb väljale "Õpperühma õppurid", siis seal on tühjus.
![image](https://user-images.githubusercontent.com/36628933/46127928-c099d980-c23a-11e8-8ee3-47d4767fe5fb.png)

Ta on mitu korda proovinud eri päevadel.
Admin töötajana saab, kuid õpetaja rollis ei saa.
Õigustega on kõik ok. Panin endale testis (HITSA koolis õpetajana) samad õigused mis temal - mina sain gruppi valida. Proovisin nii 24.sept kui 27.sept.
Päevikute juures on ta mitmel märgitud õpetajaks - seega peaks ligipääs olema.

Minu mäletamist mööda varasemalt sai ka õpetaja grupile teadet saata.
_Testitud versioonis 1.0.3_

**Comment by Lendaja** [comment]
parandus ver 1.0.4

**Comment by AnuPiirisild** [comment]
Tehtud.
