### ISSUE TITLE
Kinnitatud õppekavale ei saa versioone lisada

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#29]
Mina ei saa kinnitatud kõrghariduse õppekavale versioone lisada. Õppekava test7, muuda nuppu vajutades ei teki Salvesta nuppu.

**Comment by Pirgit** [comment]
Kinnitust ei saa ma ka maha võtta.

**Comment by irinakelder** [comment]
Kinnitatud õppekavale peab saama lisada versioone

**Comment by Lendaja** [comment]
Tehtud (v 0.3.0).

**Comment by Helenvaltmann** [comment]
korras, aitäh
