### ISSUE TITLE
Päeviku vaates valikuruutu "Näita kõik" ei uuendata peale sissekande tegemist.

### ISSUE THREAD

**Issue by kristjankivikangur** [hariduspilv/oppeinfo#292]
Kui päevikus on valik Näita kõiki maha võetud, siis lehele sissekande tegemine unustab selle ära, aga valikuruut seda ei kajasta (linnukest ei tule aga kirjed tulevad kõik). Ei tohiks unustada.

**Comment by AnuPiirisild** [comment]
Tehtud
