### ISSUE TITLE
Mobiili vaates elementide kattuvused

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#3]
![mobiili_vaate_kattuvus_1](https://cloud.githubusercontent.com/assets/17288515/24290106/6eb5c3f6-108c-11e7-9a8d-04f73c204972.png)
![mobiili_vaate_kattuvus_2](https://cloud.githubusercontent.com/assets/17288515/24290107/6eb7483e-108c-11e7-8f18-0ea852c237d6.png)

**Comment by Pirgit** [comment]
Samuti pööran tähelepanu nuppudele "Tühjenda väli", "Koosta tõend" (soovitaks nuppudel tähesuuruse vähendust).

**Comment by irinakelder** [comment]
Mobiili vaade kohendatakse peale funktsionaalsuse valmimist. Disainiga tegeletakse, sh tekstide suurused.
