### ISSUE TITLE
Õpetaja andmed

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#30]
Õpetajatele/õppejõududele lisada lisainfo või märkuste lisamise võimalus.

**Comment by irinakelder** [comment]
Lisame välja millalgi lõpus

**Comment by Pirgit** [comment]
Lisan siia juurde:
1. Õpetaja kontaktandmeid - isiklik e-post, telefon (mõlemad) peab saama õpetaja ise muuta. 
2. Administratiivne töötaja peab saama muuta kõiki teisi õpetaja andmeid (v.a isikukood). Hetkel tekkis probleem kodakondsusega, kuna isik pani ekslikult vale ning seda ei saa muuta. Samas nime peaks ka saama muuta, kui näiteks õpetaja/õppejõud abiellub.

**Comment by Lendaja** [comment]
tehtud ver 0.6.5
