### ISSUE TITLE
Õppekava otsing - Chrome'is jooksevad tekttid kokku

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#36]
Chrome’is jooksevad tekstid kokku („kestvuse periood“ ja „alates“).
 
Viga registreeritud.
![otsing- chrome](https://cloud.githubusercontent.com/assets/26483158/25524627/17e5c6fe-2c14-11e7-9c4a-7ad03e58dc3f.jpg)

**Comment by irinakelder** [comment]
Disain

**Comment by Lendaja** [comment]
Tehtud (0.3.0).

**Comment by Helenvaltmann** [comment]
korras, aitäh, kinni
