### ISSUE TITLE
Õppeaine versiooni sidumine õppekavaga, õpperühmaga

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#37]
Õppeained – kuidas toimub õppeaine versiooni sidumine õppekavaga? Õpperühmaga?  Õppeainete muutmisel peab olema võimalus muuta nö teatud versioonist ehk siis kui käesoleval aastal muutus õppeaine õpiväljundid, siis eelmiste versioonide õpiväljundid peavad säilima endisel kujul. Kopeerimise võimalus. 
Arutan lahendust arendajaga. Hetkel ei tea, et oleks õppeaine versioone planeeritud, õppekaval on versioonid.

**Comment by irinakelder** [comment]
Vt tunniplaani analüüsi
