### ISSUE TITLE
Vaadetes kattuvused

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#4]
A. Rähni: Desktop ekraanivaates on samuti kattuvusi. Kui kerida lehte alla poole, siis:
![vaate_kattuvus_1](https://cloud.githubusercontent.com/assets/17288515/24290229/dcc2fe2c-108c-11e7-9c3c-5a7350b6a118.png)

**Comment by irinakelder** [comment]
Parandatud (v 0.2.1), klassifikaatori nimetus liigub kerimisel vormiga kaasa.
