### ISSUE TITLE
Püsiandmed 

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#40]
Ei ole mõistlik küsida kohustusliku tekstiväljana „ruumi nimetus“ ja „ruumi tähis“. Üks neist võiks olla mittekohustuslik. Teksti duubeldamine.

**Comment by irinakelder** [comment]
Ruumi tähis on kohustuslik

**Comment by Lendaja** [comment]
Tehtud (v 0.3.0).

**Comment by Helenvaltmann** [comment]
toimib, panen kinni
