### ISSUE TITLE
Õppeperioodi lisamine

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#42]
Kui klikkida kuupäeva sisestamise lahtrile, viskab esimesena kalendri ette, kuigi soovin käsitsi kuupäeva sisestada. Kalender võiks avaneda vaid ikoonile klikates

**Comment by irinakelder** [comment]
Kõik peavad olema sellega nõus

**Comment by Helenvaltmann** [comment]
jah, siin olen juba teisel meelel, kui korra hiirega peale liikuda, avab kalendri aga samas ka saab kuupäeva sisestada. panen kinni
