### ISSUE TITLE
Õppekava - kinnitatud õppekavalt ei saa kinnitust maha võtta

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#44]
Kool: Kinnitatud õppekava ei saa enam muuta - peab olema muutmise võimalus! Ning kinnitatud õppekava puhul ei saa lisada uut versiooni - peab saama. 
Kinnitatud õppekavaversiooni puhul peab olema ka muutmise võimalus (st. kinnitus maha võtta ja muuta).

Hitsa kommentaar: Kinnitatud õppekava muuta ei tohi saada, tuleks enne kinnitus maha võtta. See, et kinnitust maha ei saa võtta on arendajale veana edastatud. Samuti on arendajale edastatud viga seoses uue versiooni lisamisega kinnitatud õppekavale.

**Comment by irinakelder** [comment]
1. Kinnitatud kava juures otsinguvormil Muuda linki ei kuvata
2. Kinnitaja õigusega admin töötaja saab muuta kava andmeid (va põhiandmed nagu EAP/EKAP, õppetase jms), muuta saab avades read-only vormi ja vajutades nuppu Muuda
3. Muuda nupu vajutamisel kuvatakse hoiatus "Õppekava on EHISes kinnitatud. Kas soovid jätkata?".
4. Staatus jääb endiselt kinnitatuks

**Comment by Lendaja** [comment]
Tehtud (v 0.3.0).
Kinnitatud RÕK'i ei tohi muuta. 

Kinnitatud kutsekaval ei saa muuta järgmiseid andmeid: 
-õppekava loomise viis 
-põhiandmed 
-õppekava nimetus 
-omandatavad kutsed 
-ühisõppekava andmed 
-valikõpingute moodulite maht kokku, kuna see on osa ÕK kogu mahust
-õpetatavad moodulid (osa ÕK kogu mahust) va "Valikõpingud". "Valikõpingud" mooduleid peab saama lisada/muuta/kustutada


Kinnitatud kõrghariduskaval ei saa muuta järgmiseid andmeid: 
-nimetus eesti keeles 
-õppetase 
-õppekavagrupp, valdkond suund 
-õppekava kood, õpepkava htm kood 
-maht 
-õppeaeg 
-ühisõppekava andmed

**Comment by Helenvaltmann** [comment]
tehtud ja kinni
