### ISSUE TITLE
Õppekava - peaeriala andmete muutmine

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#45]
Saab näiliselt täiendada peaeriala andmeid. Pakub salvestamise võimalust  aga ei salvesta. Kui õppekava kinni panna ja uuesti lahti teha, siis ei ole tehtud muudatused salvestunud.

**Comment by Lendaja** [comment]
Tehtud (v 0.3.0).

**Comment by Helenvaltmann** [comment]
toimib kenasti. panen kinni
