### ISSUE TITLE
Õppekava - ei saa lisada peaeriala ega kõrvaleriala

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#46]
Näiliselt saab lisada peaeriala ja kõrvaleriala. Kui andmebaas muudatusi ei salvesta, siis ei peaks pakutama ka sisestamise võimalust. Hetkel laseb programm laseb andmeid sisestada ja siis peaks olema ka salvestamise võimalus ja kui antud vorm ei salvesta sisestatud andmeid, siis peaks süsteem selle kasutajale keelama, teada andma.

**Comment by Lendaja** [comment]
Tehtud (v 0.3.0).

**Comment by Helenvaltmann** [comment]
toimib, panen kinni
