### ISSUE TITLE
Õppekava - peaeriala kustutamine

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#47]
Nt peaeriala juures on punane rist (kustuta), kui sellele vajutad, siis kustutab kohe, kuid peaks ilmuma kinnitav tekst ‘Kas soovid kustutada?’ või ‘Kustutan?’ vmt (kui see on üle programmi nii, siis kustutamise puhul peab ikka olema kinnitav küsimus).

**Comment by irinakelder** [comment]
Õppekava vormil iga risti juures peab olema küsimus

**Comment by Lendaja** [comment]
Tehtud (v 0.3.0).

**Comment by Helenvaltmann** [comment]
tehtud, panen pileti kinni.
