### ISSUE TITLE
Õppeained - otsimine

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#48]
Otsida saab, annab tulemuse, vaadata ei saa, saab ainult muuta. Tuleb lisada link, mis võimaldab vaatamiseks avada.

**Comment by irinakelder** [comment]
hetkel arendajal tehtud, saab järgmise versiooniga üle anda

**Comment by Lendaja** [comment]
Tehtud (v 0.3.0).

**Comment by Helenvaltmann** [comment]
korras, aitäh, panen pileti kinni.
