### ISSUE TITLE
Õpetajad - otsingu vaate täiendamine

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#50]
Uue lisamisega kõik korras, välja arvatud, et õppejõu lisamisel annab üleval pealkirja ‘Õppejõu otsing’. Otsing: vaates tahan näha rohkem andmeid: struktuuriüksus, ametikoht, kas on aktiivne v passiivne

**Comment by irinakelder** [comment]
Lisada otsingu vormile ja tulemuste tabelisse:
1) õppeasutuse ametikoht
2) kas aktiivne õpetaja
3) Kehtivate ametikohtade struktuuriüksused (ainult kõrg)

**Comment by Helenvaltmann** [comment]
Olemas, aitäh, panen pileti kinni
