### ISSUE TITLE
Käskirjad - kooskõlastajad

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#51]
KÄSKKIRJADE KOOSKÕLASTAJAD: lisamisel peab olema enne isik, keda lisan, sisestatud kooli töötajana (kellel juba on programmis kasutajakonto), praegu saab lisada ükskõik keda.

**Comment by irinakelder** [comment]
Kooskõlastaja ei pea olema sisestatud ÕISi (arutati analüüsi koosolekutel)

**Comment by Helenvaltmann** [comment]
mis me sellega siis teeme? hetkel saab jah sisestada ka mitte kasutajaid, kas seome ikkagi kasutajatega?

**Comment by Lendaja** [comment]
Käskkirjade kooskõlastajad on need töötajad, kelle töölauale EKISes tuleb see käskkiri. See töötaja ei pea olema kuidagi seotud ÕISiga.

**Comment by Helenvaltmann** [comment]
siis on arusaadav, ju on see jutt juba ka läbi käinud aga ma pole tähele pannud. aitäh!
