### ISSUE TITLE
Üldteated - kujundus

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#52]
Kool: ÜLDTEATE HALDAMINE: saab lisada ja muuta. Pärast ei saa näha enam sisu, saab vaid muuta.

Hitsa kommentaar: Saab nüüd ka vaadata. Üldteadete vaatamist tuleb kujunduslikult parendada.

**Comment by irinakelder** [comment]
Lisada üldteate vaatamise vormile (avaleht) link "vaata" ja "peida"

**Comment by Lendaja** [comment]
Tehtud (v 0.3.0).

**Comment by Helenvaltmann** [comment]
Toimib. Aitäh!
