### ISSUE TITLE
Automaatsed teated

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#53]
AUTOMAATSETE TEADETE MALLID: saab lisada ja muuta. Pärast ei saa näha enam sisu, saab vaid muuta.

**Comment by irinakelder** [comment]
Read-only režiim puudub

**Comment by Lendaja** [comment]
Tehtud (v 0.3.0).
Link teate liigil suunab vaatamise vormile.

**Comment by Helenvaltmann** [comment]
Korras. Aitäh!
