### ISSUE TITLE
Õppekava - mooduli liik ja mooduli nimetus

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#54]
Kool: Mis vahe on ‘mooduli liik’ ja ‘mooduli nimetus’? Meie arusaama järgi on see dubleerimine.
Kas on mõeldud, et mooduli liik on nt praktika, valikained vmt? Sel juhul peaks olema antud hüpikmenüüs vastavad valik (mida iga kool saaks ise sisestada püsiandmete all).'

Hitsa:

Siinkohal valitakse Mooduli liik all kas üldõpingute või põhiõpingute moodul. Lisame selle muudatuste nimekirja.

**Comment by irinakelder** [comment]
"Muu" on alati esimene, muud sisestatud mooduli liigid peavad olema tähestiku järjekorras läbisegi mooduli liigi klassifikaatoriga. Mooduli nimetust automaatselt ei väärtustata

**Comment by Lendaja** [comment]
Ei saa aru, mida/kas peaks tegema.
