### ISSUE TITLE
Väljal - "Mooduli hindamiskriteeriumid eesti keeles" puudub vorming

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#56]
![mooduli_hindamiskriteeriumid_vorming](https://cloud.githubusercontent.com/assets/17288515/26779533/67601cfa-49ee-11e7-9d17-9798a51323ba.png)

**Comment by Lendaja** [comment]
Palun täpsustada, milline vorming.

**Comment by Pirgit** [comment]
Kui Mooduli õpiväljundid puhul saan ma lisada erinevaid ridu (pildil näha), siis hindamiskriteeriumite puhul on teksti võimalik sisestada ühes reas ja kast ei lähe ka suuremaks.

**Comment by Helenvaltmann** [comment]
mina ei näe ega leia enam probleemi üles, panen kinni
