### ISSUE TITLE
Õppekava sisestamine - Õpetatava mooduli lisamine - kasutaja vaade Firefoxis katki

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#57]
Õppekavad - Kutseõppe õk sisestamine - Lisa moodul, vaade on Firefoxis katki. Chromes on korras.
![github1](https://user-images.githubusercontent.com/26483158/27072955-d2770a98-502a-11e7-9a3a-ded980c15782.jpg)
Pilt lisatud

**Comment by Helenvaltmann** [comment]
Õppekavad- avad kutseõppe kava - Õppekava moodulite rakenduskavad - Lisa uus - klikkad mooduli peal. Õpetava mooduli vaatamine - vaade Firefoxis katki. Chromes korras. Vaata pilti
![mooduli vaatamine](https://user-images.githubusercontent.com/26483158/27828244-db6dab58-60c3-11e7-94ed-373db76084a2.jpg)

**Comment by Lendaja** [comment]
Tehtud v 0.4.0

**Comment by Helenvaltmann** [comment]
ok
