### ISSUE TITLE
Õppekava sisestamine - Õppeasutuse kinnitamise info vorming paigast ära

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#58]
Õppekavad- Kõrghairudsõppe õk sisesatmine - õppeasutuse kinnitamise info - vorming paigast ära. Pilt lisatud. (esineb Chrome'is ja Firefoxis
![github2](https://user-images.githubusercontent.com/26483158/27079685-527df506-5041-11e7-9693-84e56e6bbc92.jpg)
)

**Comment by Lendaja** [comment]
Tehtud v 0.4.0

**Comment by Helenvaltmann** [comment]
ilus, kinni
