### ISSUE TITLE
Mõistete kasutamine

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#6]
Palun muuta süsteemis (dokumentides ei ole vajalik v.a kasutusjuhendid) järgnevaid mõisteid:
- tudeng ja õpilane = ÕPPIJA
- õpetaja, õppejõud = ÕPETAJA/ÕPPEJÕUD (kõrgharidusstandardis jaguneb ÕPPEJÕUD seitsmeks ametikohaks, millest vaid 1 on ÕPETAJA https://www.riigiteataja.ee/akt/13255227?leiaKehtiv#para14 )
- Immatrikuleerimine, õpilaste nimekirja arvamine = ÕPPEASUTUSSE VASTUVÕTMINE
- Eksmatrikuleerimine, õppeasutusest välja arvamine = ÕPPEASUTUSEST VÄLJAARVAMINE (kokkukirjutatuna)

**Comment by irinakelder** [comment]
Palun õppuri ja õpetaja mõistete muutmiseks eraldi kirja, kuna need mõisted on hanke dokumentatsioonis.

**Comment by Helenvaltmann** [comment]
arutame läbi

**Comment by Pirgit** [comment]
Juhtrühma otsusega vajalik täita!

**Comment by Pirgit** [comment]
Juhtrühma otsus, mis on veel täitmata. Kuna õpetaja/õppejõud on liiga pikk väljend, kas saab lisada nii, et kui on kutsekool, siis kuvatakse õpetaja ja kui on kõrghariduskool, siis õppejõud. Kui on mõlemad, siis õpetaja. 

Vajalik muudatus süsteemis. Kasutusjuhendites viime muudatused ise sisse ning detailanalüüsis muudatusi sisse ei vii. 

Teostada vajalik enne projekti lõppu 30.06.18.

**Comment by Lendaja** [comment]
Juhtrühma 03.04.17 OTSUS: 3.1 P. Kahro koostab ametliku kirja Fujitsu Estonia AS-le, millega palub muuta hankemenetluses toodud mõisteid „õppur“ = „õppija“ ja „õpetaja“ = „õpetaja/õppejõud“. 

Realiseeritakse:
1) "õppur" = "õppija" 
2) "õpetaja" = "õpetaja" < ei muutu, juhul, kui on kutsekool või on koolis nii kutse- kui kõrgharidusõpe 
3) "õpetaja" = "õppejõud", juhul, kui on koolis kõrgharidusõpe.

Mõistete "immatrikuleerimine" ja "eksmatrikuleerimine" muutmise vajaduse täpsustab tellija edaspidi.

**Comment by Lendaja** [comment]
Tehtud asendus "õppur" = "õppija" ver 1.0.0

**Comment by AnuPiirisild** [comment]
õpetaja>õppejõud endiselt asap vajadus. Pilet tõstetakse JIRAsse üle.
