### ISSUE TITLE
Õpperühmad - õpperühmade otsing - rühm ei ole avatav

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#60]
Kui avada õpperühad - õpperühmade otsing, peaks õpperühm Tähise väljal olema avatav. Hetkel on vaid Muuda nupp

**Comment by Helenvaltmann** [comment]
![opperuhm](https://user-images.githubusercontent.com/26483158/27228691-57f71892-52b1-11e7-9d74-ec195e789ef2.jpg)

**Comment by Lendaja** [comment]
Tehtud v 0.4.0

**Comment by Helenvaltmann** [comment]
korras
