### ISSUE TITLE
Õppekava- tudengi vaade - IT Kolledž

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#64]
Kooli kommentaar: Arusaamatuks jäi kas kõik väljad on nähtavad ka tudengile, ka need mis on täitmata (näiteks valikuvõimalused õppekava läbimiseks jne)

Heleni kommentaar: Vaja Pirgitiga arutada kuidas see mõeldud on. Demos on hetkel Jüri Õppur 50101010009  Kasutajad all määratud Kasutajaroll Õppur - Kasutajaõigused - Administratiivse töötaja õigus - Vaatamine/Otsing aga mingil põhjusel saab ta teha kõike - muuta õppekavu, lisada kasutajaid jne. Testijad on vist liiga agaralt katsetanud:)

**Comment by Helenvaltmann** [comment]
arutame õpilase vaate asja

**Comment by Lendaja** [comment]
ver 0.4.0 - tehtud rollide menüü vaated

**Comment by Helenvaltmann** [comment]
tänud
