### ISSUE TITLE
Õppekavad - väli : Õppeasutuse kinnitamise info  - IT Kolledž

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#65]
Kooli kommentaar: Õppeasutuse kinnitamise info-  pisut norivalt aga akrediteerimise otsus ei tule õppeasutuselt ja see ei ole ka korrektne väli:  Hetkel kehtiva süsteemi järgi on kõigepealt õppe läbiviimise õigus (tähtajatu või tähtajaline ja EKKA Kvaliteediagentuuri hindamisotsuse number ja kuupäev); institutsionaalse akrediteerimise otsus (akrediteerida (perioodi pikkus) ja kuupäev) ja õppekavagrupi kvaliteedi hindamise otsus (periood ja kuupäev).- Olen kuulnud, et on kavas hakata koondama institutsionaalset akrediteeringut õppekavagrupi hindamisega, aga minu teada seda otsust veel ei ole.

Heleni märkus: Pirgitiga arutada

**Comment by Helenvaltmann** [comment]
seda ei ole ükski teine kool välja toonud, kas küsida kõigilt, arutame

**Comment by Lendaja** [comment]
ei ole kohustuslikud väljad, ei pea sisestama
