### ISSUE TITLE
Õppeained  - Lisa uus - Õppeaine kood - võiks olla ühtne andmebaas - IT Kolledž

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#66]
Kooli kommentaar: Õppeainete koodidel peaks olema andmebaas.- tean, et ka TTÜ ÕIS’is ja ka rakenduskõrgkoolide ÕIS’is praegu õppeaine sisestaja peab ise eraldi andmebaasi õppekavade koodide kohta, aga loogiline oleks, et süsteem pakub koodi –ilmselt suur arendus, aga oluline.

Heleni kommentaar: tuleb arutada ja tõenäoliselt on juba arutatud kah:)

**Comment by Helenvaltmann** [comment]
arutame asja, kas peaks veel teistelt koolidelt küsima

**Comment by irinakelder** [comment]
Lepiti kokku, et esimeses etapis kindlasti ei tee
