### ISSUE TITLE
Õppekava või mõne muu kaardi sisestamine samaaegselt 

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#69]
Rektorite nõukogu üritusel küsiti, et kuidas toimib programm siis kui näiteks õppekava sisestavad samaaegselt mitu inimest. Lubasin küsimuse kirja panna ja mingi aeg ka testida.

**Comment by Helenvaltmann** [comment]
mina ei saa aru miks peaks mitu inimest korraga õppekava sisestama aga arutame korra läbi või siis testime

**Comment by Lendaja** [comment]
Sellepärast on lemas õiguste süsteem, et ainult need inimesed sisestavad andmeid, kes teavad , mida võib teha.
Kui 2 töötajat korraga sisestavad ühte ja sama õppeava, siis salvestub selle töötaja oma, kes esimesena salvestab, Kui teine paneb õppekavale sama koodi, siis saab vea, kui teistsuguse, siis salvestatakse ka tema õppekava.    
Kui 2 töötajat sisestavad erinevaid õppekavu, ei ole probleemi.

**Comment by Helenvaltmann** [comment]
toimib
