### ISSUE TITLE
Õpetaja sisestamisel emakeel kohustuslikus

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#7]
Õpetaja sisestamisel ei ole algselt emakeel kohustuslik, kuid peale kõikide teiste väljade sisestamist muutub kohustuslikuks. 
Miks ei ole koheselt kohustuslik?

**Comment by Pirgit** [comment]
Ma saan aru, et emakeel on kohustuslik ainult kutseõppes ja kõrghariduses ei ole. Hetkel tekitab see segadust õpetaja sisestamisel, et miks mingi hetk muutub kohustuslikuks.

**Comment by irinakelder** [comment]
Võtame kohustuslikkuse maha (EHISe andmevahetuse jaoks see ei ole hetkel kohustuslik)

**Comment by Helenvaltmann** [comment]
korras, panen kinni
