### ISSUE TITLE
Õppekavad - õppekava versioonid - kõrvaleriala lisamine - vaade katki

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#70]
Õppekavad - avan kinniatud õppekava - õppekava versioonid - Lisa uus -õppekava versiooni põhiandmed - Lisa kõrvaleraiala - vaade on katki. Pilt lisatud
![korvaeeriala lisamine](https://user-images.githubusercontent.com/26483158/27678117-b147b1d0-5cbc-11e7-88cb-a5e2c2c746cb.jpg)
Testitud Firefoxis. Chrome'is on kena!

**Comment by Helenvaltmann** [comment]
Sama teema on kui valida Lisa moodul ja Õpetatava mooduli lisamine

**Comment by Lendaja** [comment]
Tehtud v 0.4.0

**Comment by Helenvaltmann** [comment]
ok, aitäh
