### ISSUE TITLE
Õppekavad  - õppekava versioonid - Moodulid/Lisa kõrvaleriala- vaade katki

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#71]
Moodulid/Lisa kõrvaleraiala katavad teksti. Pilt lisatud
![oppekava versioonid](https://user-images.githubusercontent.com/26483158/27678262-425b4056-5cbd-11e7-8e90-d29ae8e3eb79.jpg)

**Comment by Lendaja** [comment]
Tehtud v 0.4.0

**Comment by Helenvaltmann** [comment]
ilus, kinni
