### ISSUE TITLE
Õppekavad - kuvab koolil kutseõppekava ka siis kui õppetasemed on märgitud vaid kõrhariduse omad.

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#72]
Logisin sisse kasutajaga 47810010020. EBS - neil on õppetasemed märgitud 511, 614 ja 734 - baka, magister ja doktor. Õppekavade all kuvab kutseõppekavade sisestamine, mida varem ei olnud.
Ma ei tea kas see on nüüd ohtrast testimisest ja seadistamisest või millest see olla võib? :) See on nii ka teistes koolides, kuhu viimasel ajal loginud olen. Pilt lisatud
![ebs_oppekavade kuvamine](https://user-images.githubusercontent.com/26483158/27679389-4220a5d2-5cc1-11e7-9177-f26ebfb7b2be.jpg)

**Comment by Lendaja** [comment]
"kuvab koolil kutseõppekava ka siis kui õppetasemed on märgitud vaid kõrghariduse omad" - lisatud õppekavad kuvatakse sõltumata kooli õppetasemest

**Comment by Helenvaltmann** [comment]
ma arvan, et see oli demo andmete sisestamisest sassis, sest praegu kuvab õppekavasid kenasti vastavalt õppekavale. Panen pileti kinni
