### ISSUE TITLE
Püsiandmed- üldteadete haldamine - kuupäeva vorming paigast ära

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#73]
Kuupäeva vorming on natuke paigast ära. Kuvamise alguskuupäev ja kuvamise lõpukuupäev ei ole samas formaadis ja nooled on natuke nihkes. Pilt lisatud
![kuupaeva vorming](https://user-images.githubusercontent.com/26483158/27686299-e0f0711a-5cda-11e7-8206-d619d3173a9b.jpg)
esineb Chrome'is ja Firefoxis

**Comment by Lendaja** [comment]
Tehtud v 0.4.0

**Comment by Helenvaltmann** [comment]
tänud, kinni
