### ISSUE TITLE
Käskkirjad - Käskkirjade otsing - kuupäeva vormingud paigast ära

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#75]
Kinnitamise kuupäev alates, Kinnitamise kuupäev kuni - väljade vorming on paigast ära. Sama on koostamise kuupäevadega vorminguga. Pilt lisatud
![kaskkirjade otsing](https://user-images.githubusercontent.com/26483158/27730948-d8a53536-5d93-11e7-8293-aa15158625da.jpg)

**Comment by Lendaja** [comment]
Tehtud v 0.4.0

**Comment by Helenvaltmann** [comment]
tänud ,korras
