### ISSUE TITLE
Õppetöö - õpingukavad - kirjaviga vormil 

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#76]
Vormil on kirjaviga - Koorduvkuulamine. Pilet lisatud
![opingukavad](https://user-images.githubusercontent.com/26483158/27787995-871280a8-5fef-11e7-8fac-20f120a148f5.jpg)

**Comment by Helenvaltmann** [comment]
Siin on lisaks veel üks väike asi. Kui läbivalt on programmis nupud Otsi, Tühjenda väljad, Lisa uus, siis siin on Lisa uus kahe nupu vahel. Võiks minu meelest ka tõsta Lisa Uus paremale poole.

**Comment by Lendaja** [comment]
Tehtud v 0.4.0

**Comment by Helenvaltmann** [comment]
tänud, kinni
