### ISSUE TITLE
Õppetöö - õpingukavad - Muuda õppekava - Muuda õppekava - vormil kirjaviga

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#77]
Nupp - Võta kinnituse maha peaks olema Võta kinnitus maha.
Pilt lisatud.

**Comment by Helenvaltmann** [comment]
![opingukavad1](https://user-images.githubusercontent.com/26483158/27788104-f21c17ec-5fef-11e7-98dc-18104776da74.jpg)

**Comment by Lendaja** [comment]
Tehtud v 0.4.0

**Comment by Helenvaltmann** [comment]
Ei saa mingil põhjusel õpingukava lisada. Kui valida Õppetöö - Õpingukavad - siis tuleb süsteemi viga 
![opingukavad](https://user-images.githubusercontent.com/26483158/31075972-c17004b8-a780-11e7-85cf-34e1cfb9ad68.png)
Ei lase ka õppeperioode ega tudengit valida
![opingukavad2](https://user-images.githubusercontent.com/26483158/31076019-0480f3f2-a781-11e7-9217-e2dc95129891.png)

**Comment by Lendaja** [comment]
Viga tekkis,  kuna ei olnu ühtegi õppeperioodi sellele koolile sisestatud. Ka õppeaasta algus ja lõpp puudusid.

**Comment by Helenvaltmann** [comment]
aitäh, edaspidi tean:)
