### ISSUE TITLE
Tõendid -sisestamine - kuupäeva valik

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#78]
Hetkel saab tõendeid sisestada tänase kuupäevaga.
Mul tekkis küsimus, et kas ma saan tõendeid ka takkajärgi sisestada või koolid nii ei toimeta?
Panin igaks juhuks kirja, arutame:)

**Comment by Helenvaltmann** [comment]
täpsustan, et hetkel kuupäeva valikut ei olegi, vaid sisestatakse arvuti kuupäev

**Comment by Helenvaltmann** [comment]
kust tuleb tõendite nummerdamine? Kas koolid saavad ise tulevikus mingeid numbriseeriaid määrata? Hetkel on väli tühi.

**Comment by Helenvaltmann** [comment]
arutame läbi kas peaks saama takkajärgi või etteulatuvalt kuupeävaga teha

**Comment by Lendaja** [comment]
ÕIS-i poolt esitatakse soov tõendi koostamiseks EKISes. EKISe poole lähevad tõendi andmed teele siis, kui vajutatakse nuppu tõendi tellimiseks. Kui Tõendile soovitakse mingisugust suvalist kuupäeva panna, siis võib seda EKISes teha.  
Numbri paneb tõendile EKIS.

**Comment by Helenvaltmann** [comment]
selge, aitäh
