### ISSUE TITLE
Õppetöö - õppetöö graafiku legend - muudatusettepanek - Muuda nupu lisamine

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#79]
Õppetöö graafiku legendi rea muutmisel peab hiirega liikuma rea peale. Kustutamise rist on kenasti olemas aga selleks, et muuta, peab teadma, et tuleb reale liikuda. See on nüüd kas koolitamise küsimus või teha ikkagi sarnaselt läbiva loogikaga, et on MUUDA nupp?
![oppetoograafikulengend](https://user-images.githubusercontent.com/26483158/27829435-4cde80cc-60ca-11e7-939c-77f6451b0986.jpg)

**Comment by Helenvaltmann** [comment]
siin peaks arutama. koolitusel oli sama teema, et nad ei osanud intuitiivselt reale liikuda, et muuta. Aruame mis teha

**Comment by Lendaja** [comment]
Pole mõtet asjatult nuppu lisada. Koolides on paar inimest, kes teevad tunniplaani, siiski koolituse küsimus.

**Comment by Helenvaltmann** [comment]
ehk tõesti
