### ISSUE TITLE
Õpetajat ei saa sisestada ilma isikukoodiga

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#8]
Peaks saama salvestada õpetajat ka nii, et on ainult sünniaeg.

**Comment by irinakelder** [comment]
Kui isikukood on sisestamata, siis peab olema synni kp, kodakondsus, sugu

**Comment by Lendaja** [comment]
Tehtud (v 0.3.0).

**Comment by Helenvaltmann** [comment]
korras, aitäh, panen kinni
