### ISSUE TITLE
Õppurid - õppurite otsing - õppuri kaardil Dokumendid lehe kuvamine katki 

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#80]
Kui avada õppurid - õppurite otsing ja avada suvaline õppuri kaart ning valida õppuri kaarid Dokumendid leht, siis on punane joon endiselt Puudumistõendid lehel. Peaks olema Dokumendid all. Firefoxis katki, Chrome'is korras. vaata pilti. 
![dokumendid](https://user-images.githubusercontent.com/26483158/27829674-63636e60-60cb-11e7-81a2-109936507683.jpg)

**Comment by Lendaja** [comment]
Tehtud v 0.4.0

**Comment by Helenvaltmann** [comment]
kena
