### ISSUE TITLE
Õppeained - Õppeaine lisamine - Kohustuslikud, soovituslikud ja asendusained on mitteaktiivsed

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#83]
Kui lisada Õppeainet, siis väljad Kohustuslikud eeldusained, soovituslikud eeldusained ja asendusained on vaates justkui mitteaktiivsed ja suurema fondiga. Minu meelest võiksid olla sama fondiga ja aktiivsed nagu teised valikuväljad (funktsionaalsus  toimib nii nagu peab) Pilt lisatud
![eeldusained](https://user-images.githubusercontent.com/26483158/29024295-0fc242da-7b7a-11e7-886d-4e387a0fc0be.jpg)

**Comment by Helenvaltmann** [comment]
Puuduvad noolekesed, mis näitavad, et saab eeldusaineid valida.

**Comment by Helenvaltmann** [comment]
kuna see ei olnud Lembele suunatud, siis on ikka nii. Lembe palun vaata kas peab nii olema?

**Comment by irinakelder** [comment]
Teha disaini parandus

**Comment by AnuPiirisild** [comment]
Tehtud.
