### ISSUE TITLE
Päringud - õppurite statistika - Õppekava väli mitteaktiivne ja puudub valiku nooleke -funktsionaalsus toimib

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#84]
Pilt lisatud
![oppurite statistika](https://user-images.githubusercontent.com/26483158/29062293-ca5a65d2-7c29-11e7-9f63-0530d14dcf05.jpg)

**Comment by Helenvaltmann** [comment]
Päring - Õppurite statistika perioodis - Õppekavaga sama teema. Uues tarnes üle vaadata

**Comment by Helenvaltmann** [comment]
see on samas seisus. Sellega pole kiiret aga panen Lembele ka:)

**Comment by Lendaja** [comment]
ee on autocomplete väli, peab hakkama lihtsalt sisestama

**Comment by Helenvaltmann** [comment]
aitäh
