### ISSUE TITLE
Päringud - Õpetaja koormus - õppeaine ja õpetaja nimi - noolekesed valikukastidest puudu

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#85]
pilt lisatud.
Vaatan järgmises tarnes üle
![opetaja koormus](https://user-images.githubusercontent.com/26483158/29062414-4d57220e-7c2a-11e7-930d-068fbb7f7339.jpg)

**Comment by Helenvaltmann** [comment]
sama  teema, hakkad lihtsalt sisse kirjutama

**Comment by Pirgit** [comment]
Proovisin täna õpetajate koormuse aruannet - annab süsteemi vea kohe kui päring avada.

**Comment by Helenvaltmann** [comment]
ma vaatasin, et tööbaasis toimib ja saab otsida aga testbaasis tuleb tõesti kohe avamisel teade Süsteemi vig.
