### ISSUE TITLE
Õpetaja "töösuhe peatatud"

### ISSUE THREAD

**Issue by Pirgit** [hariduspilv/oppeinfo#9]
EHIS-es on õpetaja ametikoha juures kohustuslik väli „Töösuhe peatatud“, valikud „Ei“ või Jah“. ÕIS-is seda ei ole. On vaid lapsehoolduspuhkuse märkimise variant, aga töösuhte peatumiseks on ka veel muid võimalusi.

Kuidas me seda lahendame?

**Comment by irinakelder** [comment]
Vaatame EHISest järgi, wsdl-s pole

**Comment by Lendaja** [comment]
Tehtud (v 0.3.0).

**Comment by Helenvaltmann** [comment]
olemas, pilet kinni
