### ISSUE TITLE
Õppekava- Kutseõppekava sisesatmine- Õppekava struktuur - lisada 4000 tähemärgi asemel 20 000 tähemärgi sisestamise võimalus

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#90]
JKHK -  Väljale   õppekava struktuur on antud liiga väike maht - siiani oleme kirjutanud   õppekava sellesse osasse põhiõpingute moodulite nimetused koos mahtude ning   õpiväljunditega ja valikõpingute valimise võimalused. Proovisin ühe viimati   EHIS-es kinnitatud õppekava struktuuri sisestada, kuid maht läks lõhki
--
HITSA: Hetkel   on võimalik sisestada 4000 tähemärki. Edastame arendajale soovi, et oleks   võimalik sisestada kuni 20 000 tähemärki.
--

**Comment by Lendaja** [comment]
Tehtud v 0.4.0

**Comment by Helenvaltmann** [comment]
nüüd on 20000
