### ISSUE TITLE
Õppekava- Kutseõppekava sisestamine - Lisada Mooduli õpiväljundite muutmise ning järjestuse määramise võimalus

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#91]
JKHK - Mooduli   õpiväljundite sisestamisel ei ole võimalust muuta juba sisestatud   õpiväljundit, seda saab ainult kustutada. Juhul, kui näiteks on tekstis   kirjaviga, siis asja korda saamiseks tuleb õpiväljund ära kustutada ja uuesti  sisestada. 
Süsteem tundub määravat omaalgatuslikult õpiväljundite järjekorra,   reastamine toimub õpiväljundi algustähe järgi. Tegelikult on õpiväljunditel   oma järgnemisloogika, tähestikuline järjestamine ei sobi. Peaks ise saama   määrata õpiväljundite järgnevuse, samuti võiks olla võimalus õpiväljundite   järjekorda pärast nende salvestamist muuta.
--
HITSA:  Edastame   muutmisevajaduse arendajale.
--

**Comment by Lendaja** [comment]
Tehtud v 0.4.0

**Comment by Helenvaltmann** [comment]
saab muuta, saab kustutada
