### ISSUE TITLE
Õppekava- Rakenduskava - Mooduli mahu jaotus - lisada mahuühiku täpsustus

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#92]
JKHK - 
Rakenduskava   sisestamisel ei ole  aru saada, mis   ühikutes tuleb mooduli mahtu näidata, kas tundides või EKAP-ites.
--
HITSA: Edastame   muutmisevajaduse arendajale.
--
Pilt lisatud
![mooduli mahu jaotus](https://user-images.githubusercontent.com/26483158/29311207-91a9f56e-81b9-11e7-8f71-df5772268030.jpg)

**Comment by Lendaja** [comment]
Tehtud v 0.4.0

**Comment by Helenvaltmann** [comment]
tunnid kenasti olemas, tänud ja kinni
