### ISSUE TITLE
H&F Õppekava- Kutseõppekava sisestamine - Lisada hoiatus, moodulitesse/teemadesse pandud mahud ei klapi moodulite mahuga

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#93]
JKHK- Võiks   olla kontrollerid arvutustel -  kui   näiteks moodulisse või teemasse sisestatud tundide üldmaht ületab mooduli   jaoks märgitud mahu, siis tuleks hoiatus.
--

HITSA: Hetkel   teavitab programm kui kutse/osakutse maht ei ole vastavuses õppekava kogu   mahuga. Arendajale edastatud soov, et kui moodulitesse/teemadesse pandud   mahud ei klapi moodulite mahuga, siis tulebks hoiatus. **Kas lubab siiski   salvestada või ei lase salvestada?**
--

**Comment by Helenvaltmann** [comment]
JKHK - Jah,   lubab salvestada. Näiteks hobuhooldaja õppekavas sisestasin mooduli   hobumajanduse alused (üldmaht 7 EKAP-it) jaotuse nii - auditoorseid tunde   999, iseseisev õpe 100, praktiline töö 300. Kokku seega 1399 tundi (aga 7   EKAP-it on 186 tundi). Ainult siis ei lase salvestada, kui panna ükskõik   millise õppeliigi tundide mahuks 1000 või rohkem tundi.     Samuti on võimalik sisestada moodulisse teema, mille tundide üldmaht ületab   mooduli enda üldmahtu.
--

**Comment by Helenvaltmann** [comment]
arutame koos läbi

**Comment by irinakelder** [comment]
Teha mooduli mahu kontroll (hoiatuse tasemel)
Lisada salvestamisel kontroll, et mooduli mahu jaotus tundides ja õppeaastate lõikes vastaks mooduli EKAP mahule.  Kui mooduli mahu jaotus ei ole mooduli EKAP mahuga vastavuses, kuvada kasutajale hoiatus „Mooduli mahu jaotus (tundides või õppeaastate lõikes) ei klapi kokku mooduli EKAP mahuga, kas soovid jätkata?“

Mooduli mahu jaotus sisestatakse kas käsitsi mooduli vormil (kui teemat ei ole) või siis arvutatakse moodulisse lisatud teemade põhjal

**Comment by Lendaja** [comment]
Tehtud ver 05
