### ISSUE TITLE
Õppekava - Kutseõppekava sisestamine - Mooduli teemade hinde kujumine - lisada võimalus "teemat ei hinnata" vms

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#94]
JKHK - Mooduli   teemade puhul ei tohiks minu arusaamist mööda olla kohustuslik täita teema   hinde kujunemist, kuna teemade hindamine ei ole kohustuslik. Või siis võiks   olla võimalik valida märkeruut "teemat ei hinnata" vmt.
--
HITSA: 

Seda   peab arutama ka teistega, kuna eelenavlt ei ole sellist nõuet esitatud.
--

**Comment by Helenvaltmann** [comment]
JKHK - Seda   võiks siis arutada küll, sest praegu ÕIS2-s saab küll salvestada rakenduskava   ilma teemasid lisamata, aga kui on soov siiski teemad lisada, siis peab   kindlasti olema ka teemade hindamine kirjeldatud, ilma selleta ei lase teemat   salvestada.
--

**Comment by Helenvaltmann** [comment]
arutame koos Lembega

**Comment by Helenvaltmann** [comment]
Pidasin Pirgitiga nõu ja võtame maha.
Kui mõnel ikkagi on kohustuslik, siis peavad oma õppekorraldusega selle asja korda ajama ja kui on kunagi vaja tagasi teha, siis see tuleb meie jaoks teilt lisatasu eest.

**Comment by Helenvaltmann** [comment]
seega võtame kohustuslikkuse maha, oli selle pika ja segase jutu mõte:)

**Comment by Lendaja** [comment]
lisatud teemale valik "Ei hinnata"; ver 0.5.
