### ISSUE TITLE
H&F Õppekava- Kutseõppekava sisestamine - Mooduli hindamiskriteeriumid peaksid olema seotud mooduli andmetega (JKHK)

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#95]
JKHK-Mooduli   hindamiskriteeriumid peaksid minu arusaamist mooda olema seotud mooduli   andmetega, kuna hindamiskriteeriumid on ju kehtestatud koos õpiväljunditega   riiklikus õppekavas, et nende alusel kontrollida õpiväljundite saavutatust.   ÕIS2 ülesehituse järgi tundub, nagu oleks hindamiskriteeriumid puhtalt   rakenduskava teema, mida kool saab oma tahtmist järgi muuta.
--
HITSA: 
Kas   süsteem ei tohiks lasta muuta neid hindamiskriteeriume, mis tulevad riikliku   õppekava aluseks võtmisel? Palun mulle veel olemasolevat probleemi seletada,   et ma saaks paremini aru. Hetkel ei oska ma lahendust pakkuda.
--

**Comment by Helenvaltmann** [comment]
JKHK - 

Jah,   kui õppekava koostamisel on aluseks riiklik õppekava, siis on õppekava põhi-   ja üldõpingute moodulid sätestatud riikliku õppekavaga. Riiklikus õppekavas   on sätestatud ka põhi- ja üldõpingute moodulite õpiväljundid ja   hindamiskriteeriumid (RÕK lisas) ning kooliõppekava koostamisel tulevad   õpiväljundid ja hindamiskriteeriumid riiklikust õppekavast, st kool ei või   neid ise muuta. Ainus, mida kool saab ise otsustada, on valikõpingute   moodulid, RÕK-is on toodud ainult valikõpingute üldmaht.
--

**Comment by Helenvaltmann** [comment]
arutame Lembega

**Comment by irinakelder** [comment]
Teha:
1) RÕK sisestaimse vormil õpiväljundid peab saama sisestada eraldi igale reale (analoogselt kutseõppe õppekavaga)
2) RÕK alusel õppekava luues tuleb õpiväljundid kopeerida
3) Kutseõppe õppekava mooduli vormile lisada uus väli hindamiskriteerium
4) RÕKi alusel õppekava luues kopeerida mooduli hindamiskriteeriumi välja sisu
5) Rakenduskava mooduli sisestamisel hindamiskriteeriumi väljal vaikimisi tuleb kuvada õppekava mooduli juures toodud hindamiskriteeriumid

**Comment by Lendaja** [comment]
tehtud ver 0.5
