### ISSUE TITLE
Püsiandmed - Õppeasutuse õppeperioodid - Kontrollide lisamine,  õppeperiood oleks õppeaasta sees ja kevad- ning sügissemestrid ei kattukss

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#97]
JKHK-  Õppeperioodide   sisestamisel võiks olla kontrollmehhanismid - praegu lubab õppeperioodi   sisestada kuupäevi, mis ei kuulu antud õppeaastasse. Samuti lubab   õppeperioodide kuupäevadel kattuda - näiteks panna uue perioodi alguseks   kuupäev, mis kuulub eelmise õppeperioodi sisse.
--
HITSA: 

Arendajale   on saadetud järgnev muudatuse soovid: 1) Õppeaastasse sisestatud õppeperiood   peab olema õppeaasta sees; 2) Õppeaastasse sisestatud sügissemestri kuupäevad   ei tohi kattuda kevadsemestri kuupäevadega.
--

**Comment by Lendaja** [comment]
Tehtud v 0.4.0

**Comment by Helenvaltmann** [comment]
väga ilus!
