### ISSUE TITLE
Püsiandmed- Hooned ja ruumid - hoone salvestamisel võiks kuvada lisa hoone ja lisa ruum nupud

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#98]
JKHK- Hooned   ja ruumid - uue hoone salvestamisel jäävad ekraanile salvestatud hoone   andmed, aga võiks olla samal lehel ka "lisa hoone" ja "lisa   ruum" nupud, praegu peab edasi toimetamiseks valima vasakmenüüst uuesti   "Hooned ja ruumid"
--
HITSA: 

Arutame   arendajaga muudatusettepanekut.
--

**Comment by Lendaja** [comment]
"Tagasi" nupp viib otsingu vormile, kus on nupud "Lisa ruum" ja "Lisa hoone". Menüüst valima ei pea.

**Comment by Helenvaltmann** [comment]
Tagasi või uuesti valimine on sisuliselt sama, üks nupuvajutus rohkem. Kui oleks Lisa ruum ja lisa hoone samal lehel, saaks kiiremalt aga saan ka aru, et siis peaks seda hakkama programmis ju igale poole lisama, nii et jah...

**Comment by Helenvaltmann** [comment]
ma panen selle pileti kinni, see on seotuna teise teemaga ja kui teha ühes kohas siis võiks mõelda kus ja kas veel. see probleem on ikkagi siis kui alguses pannakse palju andmeid sisse. Kui need üle tuuakse, siis langeb samuti probleem ehk ära
