### ISSUE TITLE
Püsiandmed - Käskkirjade kooskõlastajad - Kooskõlastaja salvesatmisel võiks lisada nupu järgneva kooskõlastaja lisamiseks.

### ISSUE THREAD

**Issue by Helenvaltmann** [hariduspilv/oppeinfo#99]
JKHK - Käskkirjade   kooskõlastaja - salvestamisel võiks tekkida kohe nupud veel ühe kooskõlastaja   lisamiseks, praegu peab selleks valima vasakmenüüs uuesti "käskkirjade   kooskõlastaja"
--
HITSA: Arutame   arendajaga muudatusettepanekut.
--

**Comment by Helenvaltmann** [comment]
see on sama põhimõtteline küsimus nagu ruumide sisestamisel, et kas hoone salvestamise juures võiks olla kohe lisamise nupp või peab vajutama enne tagasi nuppu. Arutame, otsustame ära ja siis edapidi teab.

**Comment by irinakelder** [comment]
Teha:
Kooskõlastaja muutmise vormile ja ka ruumide muutmise vormile lisada nupud "Lisa uus". Nupule vajutades saab sisestada uus kooskõlastaja või ruum
